### ISSUE TITLE
BigNumber type check

### ISSUE THREAD

**Issue by stcherenkov** [MikeMcl/bignumber.js#100]
If I want to check type of basic BigNumber instance, I do:
```
var foo = new BigNumber('123.4');
console.log(foo instanceof BigNumber); // true
```

But if I define new BigNumber constructor using `.another()`, I get:
```
var AnotherBigNumber = BigNumber.another();
var bar = new AnotherBigNumber('123.4');
console.log(bar instanceof BigNumber); // false
```

What is the correct method of "another" BigNumber instances type-checking?

**Comment by MikeMcl** [comment]
```js
console.log(bar instanceof AnotherBigNumber);    // true
```

**Comment by stcherenkov** [comment]
In my particular case I'm defining custom React prop type that checks if passed property is BigNumber-like. It works fine until I create another constructor with i.e. custom formatting options.

There was once the same issue with moment.js. Now there is an additional method for type-checking: http://momentjs.com/docs/#/query/is-a-moment/. Implementation: https://github.com/moment/moment/blob/develop/src/lib/moment/constructor.js#L72

I could try to make a pull-request with similar behaviour for BigNumber. Does it fit the concept?

**Comment by josdejong** [comment]
What I've done in `mathjs` is add a property `isBigNumber` to the prototype:

```js
BigNumber.prototype.isBigNumber = true
```

Then you can simply check whether this property is true:

```js
console.log(bar && bar.isBigNumber)  // true when BigNumber, false otherwise
```

**Comment by MikeMcl** [comment]
@stcherenkov 

Okay, I'm open to it.
