### ISSUE TITLE
Issue with adding two decimal numbers that should result in an integer sometimes results in a NaN value

### ISSUE THREAD

**Issue by zpratt** [MikeMcl/bignumber.js#102]
You may laugh me out the door after you read this, but I swear this is real. To reproduce the issue, you'll need a 4th generation ipad. I have tested this on a myriad of other ipads and platforms and I am not able to reproduce the issue. I have ensured that we're using latest version of iOS as well (which was 10.1.1 when I opened this issue). 

This appears to be at least an issue with bignumber.js v2 and greater. My example is using the latest release.

Summary:
```js
new BigNumber(1111.2).plus(222222.8).toNumber();
```

Returns `NaN` instead of `223334` on certain generations of ipads.

Example to reproduce the issue: http://jsbin.com/xamofokeye/edit?js,output

Proof: [
![nan-proof](https://cloud.githubusercontent.com/assets/5916561/20544689/d6bd8108-b0d0-11e6-9310-9b30f1eb7052.png)
](url)

ipad models that I used for testing: MD510LL/A and MD514X/A

**Comment by zpratt** [comment]
This works as a workaround (which might help isolate the issue in the code itself):

```js
new BigNumber(1111.2 * 10).plus(222222.8 * 10).dividedBy(10).toNumber()
```

**Comment by MikeMcl** [comment]
If there is any issue here, it seems to be with that particular platform and not this library.

**Comment by rcoy-v** [comment]
#57 seems to be the same issue reported here. The proposed solution in that issue was to open a bug with Apple dev, but this problem still exists after 1 1/2 years and multiple ios versions. Is there a reasonable work-around that can be reached in this library instead?

Also, version 1.5.0 seems to work with the given example. Likely because of this:
> Store a BigNumber's coefficient in base 1e14, rather than base 10.

Rolling back versions is 1 option, but I would prefer not being locked out from active versions that are given more features/attention.

**Comment by MikeMcl** [comment]
@rcoy-v  

Thank you for finding #57. I had forgotten about that.

The bug needs to be reported at source. It is a bad bug. 

Notwithstanding that, please try replacing the for-loop at line 1856 of bignumber.js with

```js
   for ( a = 0; b; ) {
        a = ( xc[--b] = xc[b] + yc[b] + a ) / BASE | 0;
        xc[b] = xc[b] % BASE;
    }
```

Please also try

```js
    for ( a = 0; b; ) {
        a = ( xc[--b] = xc[b] + yc[b] + a ) / BASE | 0;
        xc[b] = BASE === xc[b] ? 0 : xc[b] % BASE;
    }
```


and finally

```js
for ( a = 0; b; ) {
    xc[--b] = xc[b] + yc[b] + a;
    a = xc[b] < BASE ? 0 : 1;
    xc[b] %= BASE;
}
```

**Comment by zpratt** [comment]
@MikeMcl the second fix work. I have verified this on the device that had the issue. Thank you for helping us!
