### ISSUE TITLE
Constructor for formatted number

### ISSUE THREAD

**Issue by andreasschiestl** [MikeMcl/bignumber.js#109]
First of all, thanks for the great library!

Is there a way to create a BigNumber object of a formatted number (e.g. 123,456.789)? We are currently remove the group seprator and replace the decimal separator with . before we pass the value to the constructor (our app is mainly used with german locale where , is the decimal separator).

**Comment by MikeMcl** [comment]
Thank you. 
No, there is no way.
You are probably best continuing with your current approach.

I have previously considered making the decimal separator configurable but decided that it was more trouble then it was worth.
