### ISSUE TITLE
15 significant digits for input number type is not enough

### ISSUE THREAD

**Issue by Olathe** [MikeMcl/bignumber.js#11]
The readme says "It accepts a value of type Number, String or BigNumber Object", which would be nice, but which is currently incorrect. `BigNumber(Math.random())` and `BigNumber(Math.PI)` and several other higher-precision numbers fail with the following message:

`BigNumber Error: new BigNumber() number type has more than 15 significant digits: [digits]`

This has several problems:
- `Math.random()` and `Math.PI` are valid numbers, which should be handled properly.
- If you're worried about imprecision, allowing and encouraging literal numbers is exactly the wrong thing to allow. Strings literals should be used instead in that case, as you've apparently noted. The current design makes the one decent use of accepting numbers (for example, numbers from a database where you have no control over the precision anyway) more bug-prone (because people can have code that seems to work for a while on some inputs they try and then breaks in production) while making the improper use easier.
- If you're going to allow conversion of a base two floating point number into a base ten floating point number, you're almost surely introducing error anyway. For instance, you can't tell whether the number that gives the string '0.1' is exactly 1/10 or the result of a calculation that's merely fairly close to 1/10 because of error, yet you accept that number as if it's exactly 1/10. If that possibility of error when the number is merely near 1/10 is acceptable, why not Math.PI?
- If you're going to keep the error message, the digits in the error message should include the decimal point. There's no point in showing only the digits (are people supposed to count them or something?) rather than the number itself.

**Comment by 1simonfish** [comment]
We would like the 15 digit limit removed. 

```
x = new BigNumber(Number.MAX_SAFE_INTEGER)
```

should be legal.  We're using BigNumber as a replacement for BigInteger, and having to convert legal integers to strings just to convert them to BigNumbers seems inefficient.

**Comment by igorlino** [comment]
@MikeMcl 

nice library!

> I would be interested to hear if anybody else would prefer the 15 s.d. limit to be removed.

I think it would be practical if it could be configurable, since maybe I want to work with 20 digits, without having to disable the errors.

````
BigNumber.config({ ERRORS: false });
````

**Comment by MikeMcl** [comment]
Thanks.

Can't you just convert the number to a string?

    var n = 12345123451234512345;
    x = new BigNumber(String(n));

And most 20 digit numbers can't be stored exactly as JavaScript numbers anyway

console.log(n);    // 12345123451234513000

I have removed the 15 digit limit for numbers in *decimal.js* and I may do it here, but not right now.

**Comment by Slowlearneruk** [comment]
Shouldn't the cap be Number.MAX_SAFE_INTEGER rather than 15 digits?

**Comment by MikeMcl** [comment]
No, it is a matter of significant digits rather than whether a number is an integer or float. 

Many values of sixteen significant digits or more cannot be stored precisely using JavaScript numbers (double-precision floating-point)

For example, 

    console.log(9.543245345454127)    // 9.543245345454126

**Comment by Slowlearneruk** [comment]
I wonder if it could be a little more selective - as was working with integers it was frustrating to have to from my ceiling from MAX_SAVE_INTEGER to 999999999999999. It is an excellent library BTW which this extremely minor criticism does nothing to change :)

**Comment by MikeMcl** [comment]
See #91 

From *v2.2.0*, all integers up to Number.MAX_SAFE_INTEGER are now accepted.

**Comment by mqklin** [comment]
@MikeMcl can you automatically convert arguments to `String`? Now we have to wrap every argument, very inconvenient: `toBigNumber(String(10 ** -decimals)).mul(String(quantity)).mul(String(priceItem.value.usd)));`

**Comment by MikeMcl** [comment]
@mqklin 

There is no need to convert arguments to string. You are commenting on a very old issue here which probably contains discussion that is irrelevant to later versions of this library.

Since v7.0.0 there is no error thrown on numbers with more than 15 significant digits unless a DEBUG property is added to BigNumber and set to true.

```js
BigNumber.DEBUG = true;
```

**Comment by mqklin** [comment]
@MikeMcl We use v7.2.1
That's strange, because we didn't set `DEBUG = true`

**Comment by mqklin** [comment]
Oh, we use `bignumber.js` inside `web3` lib, which uses old version: https://github.com/frozeman/bignumber.js-nolookahead - we should use the new one. 

Thank you!
