### ISSUE TITLE
Add `isBigNumber()` to allow instanceof tests across JavaScript contexts

### ISSUE THREAD

**Issue by fastfedora** [MikeMcl/bignumber.js#111]
When multiple copies of `bignumber.js` are imported, an instance created by one copy will return false for `instanceof BigNumber` if the `BigNumber` for the `instanceof` test is from a different copy.

This can occur in Node when a library imports `bignumber.js` and the main application imports `bignumber.js` and two copies exist within `node_modules`. As an example, see [this PR](https://github.com/sidorares/json-bigint/pull/14) I submitted to fix this issue for `json-bigint`.

That solution used duck-typing to detect if an object was a BigNumber. But since many objects could have `c`, `e` and `s` as keys, this isn't reliable. It would be useful if BigNumber provided an `isBigNumber` method that returned true if passed in value was a BigNumber.

As an example, the `moment` library provides `moment.isMoment()` with the following implementation:

```
function isMoment (obj) {
    return obj instanceof Moment || (obj != null && obj._isAMomentObject != null);
}
```

The `_isAMomentObject` is an additional property set on every instance to true. A similar, `_.isABigNumberObject` could be added to the instance.

The addition of `BigNumber.isBigNumber()` would allow for more reliable testing across JavaScript contexts. 

I can put together the code and create a PR if this sounds good.

**Comment by MikeMcl** [comment]
There is already a PR for this, see #101.

As you are at least the third person that has requested this in a fairly short period of time, I think I will have to reconsider my decision to reject that PR.

**Comment by MikeMcl** [comment]
`isBigNumber` method added in v3.1.0.

Thanks for raising this issue as it enabled me to discover and fix an unrelated bug.
