### ISSUE TITLE
Consider adding inRange and clamp methods.

### ISSUE THREAD

**Issue by nmsmith22389** [MikeMcl/bignumber.js#114]
Would you please consider adding [.inRange()](https://lodash.com/docs/#inRange) and [.clamp()](https://lodash.com/docs/#clamp) methods to BigNumber?

I feel as though both of these methods can save many lines of code, as of now I either have to use a longer than necessary conditional, write my own function, or convert to numbers, use another library such as Lodash, then convert back.

I'm sure you could probably even drop Lodash's functions into your own line for line.

I have my own projects but if you want help or a PR just let me know.

Thanks!

**Comment by MikeMcl** [comment]
I've considered it and I don't want to add the methods, thank you.

```javascript
BigNumber.prototype.inRange = function(lower, upper) {
  if (upper === undefined) {
    upper = lower;
    lower = 0;
  }
  return this.gte(lower) && this.lt(upper);
};

BigNumber.inRange = function(number, lower, upper) {
  return new BigNumber(number).inRange(lower, upper);
};

BigNumber.prototype.clamp = function(lower, upper) {
  if (upper === undefined) {
    upper = lower;
    lower = undefined;
  }

  return new BigNumber(
    upper !== undefined && this.gt(upper) ? upper :
    lower !== undefined && this.lt(lower) ? lower : this
  );  
};

BigNumber.clamp = function(number, lower, upper) {
  return new BigNumber(number).clamp(lower, upper);
}; 
```



```
