### ISSUE TITLE
Would be great if bignumber.js have a "convert integer to bytes method"

### ISSUE THREAD

**Issue by VictorQueiroz** [MikeMcl/bignumber.js#117]
I think would be very helpful if bignumber.js have a `toBytesLE()` and `toBytesBE()` method just like [long](npmjs.org/long) and [jsbn](npmjs.org/jsbn) modules. I'm not talking about buffers, maybe just `Uint8Array` or maybe just a simple array of numbers to represent a `Uint8Array` instance. If not possible, a good example of how to do it using `bignumber.js` would be great as well

**Comment by MikeMcl** [comment]
Those libraries are integers only - how do you think a number such as `123.456` should be represented as an array of bytes? 

It could be done, but what is the goal, what is the use-case?

**Comment by alexander-ossur** [comment]
Hi there,

I am on the same request. It is necessary for saving BigNumber into file, and then read it later

Thank you

**Comment by alvaro-alonso** [comment]
Same here @VictorQueiroz .This would be very useful when hashing bigNum (SHA-256). Commonly done on the blockchain

**Comment by MikeMcl** [comment]
@alvaro-alonso 

I did some work on this but it is incomplete and I haven't time to work on it at the moment.

I haven't used it but try [this](https://github.com/LiskHQ/lisk-sdk/blob/01bf90e32cd336417af260f4969fd12659bf5691/helpers/bignum.js).
