### ISSUE TITLE
Error in IE8: SCRIPT1010: Expected identifier

### ISSUE THREAD

**Issue by wang7x** [MikeMcl/bignumber.js#121]
Looks like the cause is the use of "default" , where "default" is a reserved string.
```BigNumber.default = BigNumber.BigNumber = BigNumber;```
change to
```BigNumber['default'] = BigNumber.BigNumber = BigNumber;```

**Comment by MikeMcl** [comment]
Thanks very much.

Fixed in v4.0.1.
