### ISSUE TITLE
How can I prevent/catch BigNumber Error: times() number type has more than 15 significant digits?

### ISSUE THREAD

**Issue by JohnAllen** [MikeMcl/bignumber.js#123]
So we have some user input that we need to perform calculations on, and every once in a while we get this error.

Is there any way to prevent or catch this without wrapping everything in a try/catch block?  We need to use this four times in a module and don't want to add a ton of try/catch blocks.

I tried `.round(14)` but that didn't work.  We actually prefer the max precision though.

**Comment by josdejong** [comment]
I think you can configure `{ERRORS: false}` see docs: http://mikemcl.github.io/bignumber.js/#errors

**Comment by morioust** [comment]
Does this option still exist in the current version?
