### ISSUE TITLE
Error parsing value with decimalSeparator=comma

### ISSUE THREAD

**Issue by mleduque** [MikeMcl/bignumber.js#126]
Hi,
I used BigNumber.config with a FORMAT with decimalSeparator set to comma.
It correctly formats the number as expected.
When I try parsing (with new BigNumber(...) ) a number with a decimal comma, the parsing fails, with for example
BigNumber Error: new BigNumber() not a number: 0,3

I see I only configured the format, used for formatting, but didn't configure the parsing.
Did I miss the parsing configuration ?

**Comment by MikeMcl** [comment]
No, there is no parsing configuration.
I have considered it before and decided against it.

**Comment by annakaz** [comment]
Note that decimal separator is now an option, see decimalSeparator https://mikemcl.github.io/bignumber.js/#format

**Comment by iwhitman2055** [comment]
> Note that decimal separator is now an option, see decimalSeparator https://mikemcl.github.io/bignumber.js/#format

This option was present back in 2017, as described by @mleduque .  However, it still doesn't affect parsing as of v8.0.2.
