### ISSUE TITLE
Issues with new type definitions

### ISSUE THREAD

**Issue by tzachshabtay** [MikeMcl/bignumber.js#131]
It seems that a new version was released today with type definitions built-in, and it takes over those in DefinitelyTyped, which broke compilation for my application.

Errors I got:

1. When writing `new BigNumber(0)`, getting `error TS2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.`
This can be fixed by replacing `BigNumber` with `BigNumber.BigNumber` but it's uglier.
A similar issue exists when writing `BitNumber.Config(...)`.

2. When writing `x.add(..)` getting `error TS2339: Property 'add' does not exist on type 'BigNumber'.`
I see that there's a `plus` method, I guess I can use it instead? Is it the same?

3. When writing `x.mul(..)` getting `error TS2339: Property 'mul' does not exist on type 'BigNumber'.`
I can't see anything in the type definition for multiplying, am I missing something?

Thanks.

**Comment by jordanluyke** [comment]
Hi @tzachshabtay, how are you importing bignumber? I would recommend `import {BigNumber} from 'bignumber.js'` or `import BigNumber from 'bignumber.js'`. For 2 and 3, I will add those methods to the definitions

**Comment by mwistrand** [comment]
If you're using either `@types/bignumber.js` or those directly from DefinitelyTyped, then you'll need to update your source to treat `BigNumber` as the default export. However, I have noticed a couple missing definitions for the alias methods (e.g., `mul` and `sub`). If that warrants a separate issue, let me know. I'd be happy to open a PR with the necessary changes.

**Comment by tzachshabtay** [comment]
I'm doing `import * as BigNumber from "bignumber.js";`.
If that's the issue with 1, I can change the imports. I'll test one there's a new release.
Thanks.

**Comment by peterblockman** [comment]
For those who come here because of `Property 'add' does not exist on type 'BigNumber'.`

It is `plus` not `add`.
