### ISSUE TITLE
Change default base in config

### ISSUE THREAD

**Issue by medisoft** [MikeMcl/bignumber.js#133]
Is there a way to change the default base in the global config?

Let suppose that i want to store all the numbers in base 64 to reduce space and bandwidth, and all the operations are done in base 64, with some exceptions in base 10. It makes sense to use a global for base 64 and specific parameter on the operations using the base 10.

Is that possible?

Thank you

**Comment by MikeMcl** [comment]
No, it isn't possible.

A configurable base was a goal at one point, but it was abandoned as I didn't think it would be useful enough to justify the work and the probable increase in the size and complexity of the library required.
