### ISSUE TITLE
iOS safari dived bug

### ISSUE THREAD

**Issue by yuxingxin** [MikeMcl/bignumber.js#134]
I found a question on my iPhone device with safari:
```
console.log(new BigNumber(3.1).dividedBy(new BigNumber(2)));   //  1.54999999999999     Precision Lost
console.log(new BigNumber(3.1).div(new BigNumber(2)));    //  1.54999999999999   Precision Lost
console.log(new BigNumber(3).dividedBy(new BigNumber(2)));     // 1.5     Normal
console.log(new BigNumber(3).div(new BigNumber(2)));     // 1.5     Normal
```
but test on my PC and my Android device with safari are well,
```
console.log(new BigNumber(3.1).dividedBy(new BigNumber(2)));   //  1.55   Normal
console.log(new BigNumber(3.1).div(new BigNumber(2)));    //  1.55   Normal
console.log(new BigNumber(3).dividedBy(new BigNumber(2)));     // 1.5     Normal
console.log(new BigNumber(3).div(new BigNumber(2)));     // 1.5     Normal
```
> BigNumber is default config

How why?

**Comment by MikeMcl** [comment]
Firstly, just in case you do not know it, there is no need to use `new BigNumber(2)`. You can just use `2`.

Next, try adding the `toString` calls explicitly, for example

`console.log(new BigNumber(3.1).dividedBy(2).toString());`

Then, try adding the following code above your code. If it fixes the issue, the problem is probably caused by the Safari bug described [here](https://github.com/MikeMcl/bignumber.js/issues/120)

```js
if (Object.keys({'250': 0.5, '1000': 0.1}).length !== 2) {
  Array.prototype.unshift = function () {
    Array.prototype.splice.apply(this, Array.prototype.concat.apply([0, 0], arguments));
    return this.length;
  };
  Array.prototype.shift = function () {
    return Array.prototype.splice.call(this, 0, 1)[0];
  };
}
```

**Comment by yuxingxin** [comment]
@MikeMcl my iOS version is 10.3.3 and Safari version is 10.0, I just confirm it's caused by Safari. When I added the following code above my code,the problem is solved. I also tested on new iOS version 11.0.2 and Safari version is 11.0, the bug is fixed.
```
if (Object.keys({'250': 0.5, '1000': 0.1}).length !== 2) {
  Array.prototype.unshift = function () {
    Array.prototype.splice.apply(this, Array.prototype.concat.apply([0, 0], arguments));
    return this.length;
  };
  Array.prototype.shift = function () {
    return Array.prototype.splice.call(this, 0, 1)[0];
  };
}
```
