### ISSUE TITLE
Feature request: configurable ALPHABET for base x

### ISSUE THREAD

**Issue by Xotic750** [MikeMcl/bignumber.js#137]
Hi,

I didn't see any similar request, but I'd like to have a config option that either allows me to choose an alternative set of ALPHABET characters, in particular an alternative 64 character set that is commonly used by other systems;

`'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+/'`

and/or to be able to completely define a custom set of 64 characters.

A further use case example might be if working with [Duodecimal](https://en.wikipedia.org/wiki/Duodecimal) where we may want to use the characters rotated 2 and rotated 3 (or A,T,X or B,E).

Thanks for consideration.

**Comment by MikeMcl** [comment]
Added in *v6.0.0*. Thanks for the suggestion.
It took a while as one change often seems to lead to another...
