### ISSUE TITLE
Why would you get rid of round + floor in 6.0?

### ISSUE THREAD

**Issue by brandonros** [MikeMcl/bignumber.js#139]

**Comment by Gemorroj** [comment]
😿 
need `round` method...

**Comment by MikeMcl** [comment]
Yes, there have been some API changes in the new major version - hopefully the last API changes for this library.

The API has been trimmed and made more consistent.

`ceil`, `floor`, `round` and `trunc` are gone, replaced with the more explicit `integerValue` method.
It wasn't necessary to have four methods to round a BigNumber to an integer!

`ceil` and `floor` are rounding modes that can be applied to rounding a BigNumber not only to an integer but also to any number of decimal places or significant digits. It made little sense to have them as methods apart from users' familiarity with the JavaScript Math methods. 

The same applies to `round`. What does `x.round(3)` mean? "Round" to what? It isn't clear.
`x.decimalPlaces(3)` and `x.integerValue()` are much clearer.

**Comment by MikeMcl** [comment]
Yes, the new major version, *v6.0.0*, brings a number of API changes.

The API has been trimmed and made more consistent.

There was no need to have four methods to round a BigNumber to an integer, so `ceil`, `floor`, `trunc` and `round` have been replaced with `integerValue`, which I think is much clearer.

This library can round to an integer or to a number of decimal places or significant digits, so a method named `round` is not specific enough. I don't want the API to be tied to following the JavaScript `Math` object.

Old way:
```js
x.round()        // round to integer
x.round(3)       // round to decimal places
x.toDigits(4)    // round to precision (i.e. significant digits)
```

New, clearer way:
```js
x.integerValue()
x.decimalPlaces(3)
x.precision(4)
```

Also, `toPower` and `toDigits` have gone, so now all the methods that begin with `to` transform a BigNumber to another type. Also, all the methods that return a boolean now begin with `is`.

**Comment by brandonros** [comment]
How would you do .floor/.ceil?

Also, you got rid of being able to do BigNumber.config({ERRORS: false});
Does this mean errors get thrown now?

Wild step back if so...

I really think these changes were a mistake. I think you may think they are
cleaner... but for people looking for a drop-in replacement in a scram...
.floor should be .floor, .round should be .round.

As similar to Math as possible.

But, I digress. You're the author/artist, your choosing... :) Thanks for
you work + efforts. Mild not thanks for breaking the code when I needed to
use it. :)

**Comment by MikeMcl** [comment]
```js
x.integerValue(BigNumber.ROUND_FLOOR)
x.integerValue(BigNumber.ROUND_CEIL)
```

Yes, errors always get thrown, but only in limited circumstances. I think this makes the library safer to use.

I resisted changing the API for a long time because it would inconvenience existing users, but I spent a lot of time on the new API and I am happy with it.

There are no new bug fixes or optimisations in the new version, so there is no reason to switch to it if you prefer the old API - unless you want the configurable `ALPHABET`.

**Comment by brandonros** [comment]
> Yes, errors always get thrown, but only in limited circumstances. I think
this makes the library safer to use.

Are you saying there's no way to catch the old "15 digit only" error now?...

**Comment by MikeMcl** [comment]
Yes, the 15 digit error can no longer be stopped ;)

**Comment by brandonros** [comment]
Yikes, between that and you getting rid of what would be like... 9 lines of
syntactic sugar for floor/round/ceil to make this library much more user
friendly by providing what people would expect to find in a number
library... wild step backwards for this package.
