### ISSUE TITLE
BigNumber being converted to an object

### ISSUE THREAD

**Issue by justinkchen** [MikeMcl/bignumber.js#140]
Im trying to work with the 0x.js project and I'm using a BigNumber, however, it is getting converted to an object and failing assertions.  Do you have any idea what could be causing this? This is on 0.4.1 version.  You can see an example in arg[1] below:

<img width="482" alt="screen shot 2018-01-30 at 2 05 47 am" src="https://user-images.githubusercontent.com/1000741/35562468-55860680-0568-11e8-9c87-4a825d3479e8.png">

**Comment by justinkchen** [comment]
I found out the issue is from a heroku buildpack (https://github.com/mars/create-react-app-buildpack.git) that is somehow packaging the BigNumber package weird when serving it statically I think...anything that you know about the package that might cause weird behavior?

**Comment by MikeMcl** [comment]
I don't know anything about heroku. I know that the presence of the *bignumber.mjs* file has caused problems for webpack if it is not configured correctly.

**Comment by justinkchen** [comment]
do you know how to properly configure mjs files? perhaps i'll try to custom configure the webpack to serve this file. this is the only package causing issues right now

**Comment by MikeMcl** [comment]
Your original question states that a BigNumber is getting converted to an object, but a BigNumber *is* an object. If you want it's value you have to call `toString()` or `valueOf()` on it. 

As for packaging issues, your question is too vague and confused.

If using webpack try `mainFields: ["main", "module"]` in the webpack config so that it uses the *bignumber.js* file instead of the *bignumber.mjs* file.

**Comment by justinkchen** [comment]
Sorry, I guess the issue is that BigNumber is being converted to an object that looks like `t { s:1, e:0, c: Array(1)}` instead of showing up as an actual instance of `BigNumber` This is most likely either an issue with webpack config or something with the serving of the js.  I will try a few things including your suggestion for the webpack config change. Thank you!!

**Comment by MikeMcl** [comment]
It is probably nothing to do with webpack. 

If you type `x = new BigNumber(123); x` in a browser console at [this](http://mikemcl.github.io/bignumber.js/) address, it will show the same thing. It is still an instance of BigNumber.

**Comment by justinkchen** [comment]
Basically when the library (0x.js) calls it, it is failing the `x instanceOf BigNumber` check that is inside of `sendTransactionAsync` (seen here: https://github.com/0xProject/0x.js/blob/development/packages/0x.js/src/contract_wrappers/token_wrapper.ts#L90).  even though from my end, I'm passing it in as `new BigNumber(0)` in the code.

**Comment by MikeMcl** [comment]
Oh, okay. I can't get too involved in this. Good luck!

**Comment by justinkchen** [comment]
Thank you! i found out it has something to do with serving the file as a static build...will look into it but appreciate your time!

**Comment by justinkchen** [comment]
Specifically I think its an issue with this here: https://github.com/ethereum/web3.js/blob/develop/package.json#L11 which is using a minified version of an old bignumber
