### ISSUE TITLE
Function integerValue is not viable

### ISSUE THREAD

**Issue by barakman** [MikeMcl/bignumber.js#141]
The [doc](http://mikemcl.github.io/bignumber.js/#int) says that this function "Returns a `BigNumber` whose value is the value of this `BigNumber` rounded to an integer using rounding mode `rm`".

When I call it like this:

    web3.toBigNumber(num).times("1e+18").integerValue(web3.BigNumber.ROUND_DOWN)

I get the following error:

    web3.toBigNumber(...).times(...).integerValue is not a function

**Comment by MikeMcl** [comment]
You are either using an earlier version of bignumber.js that dioesn't include the `integerValue` method, or there is a mistake in your code.

**Comment by barakman** [comment]
I'm using it via web3.js. Is there any chance that this function has been added very recently and I should update my web3 package?

**Comment by MikeMcl** [comment]
Yes, the method is only in *v6.0.0* which I published last week.

**Comment by barakman** [comment]
Got it, thank you very much.
