### ISSUE TITLE
typings - global Bignumber

### ISSUE THREAD

**Issue by olaf89** [MikeMcl/bignumber.js#143]
```
/**
 * Browsers.
 */
declare global {
  const BigNumber: BigNumberConstructor;
  type BigNumber = BigNumberInstance;

  namespace BigNumber {
    ...
  }
}
```
Why bignumber is this defined as global? I think this declaration should be removed cause its really error prone.

**Comment by MikeMcl** [comment]
Please explain what you mean. 
The code is necessary to use the typings outside a module loader environment, i.e. in a browser.

**Comment by olaf89** [comment]
I do use bigNumber in the browser, but i import it using es6 named imports 
```
import { BigNumber } from 'bignumber.js' 
```
But now when i skip this import, typescipt does not report any issues and its failing during runtime, cause BigNumber is not found.

**Comment by MikeMcl** [comment]
`BigNumber` would only be not found in a browser if the *bignumber.js* script isn't being loaded.
If you're not loading the script then why include the typings?

**Comment by olaf89** [comment]
Ok, the thing is that for projects in node.js & projects using module loaders including bigNumber as global object in typings is highly error prone and harms developer experience - cause you cannot use auto import.

**Comment by MikeMcl** [comment]
Please explain further.

**Comment by olaf89** [comment]
Well its very simple, i create simple file on my project (using webpack andbignumber 6.0.0)

<img width="276" alt="screen shot 2018-02-08 at 00 31 58" src="https://user-images.githubusercontent.com/11535118/35947304-82cf34bc-0c67-11e8-82c5-e38734d7eef0.png">

Its looks all good typescript is happy, then i run it and it fails.

Lets compare it to version 5.0.0 of bignumber without global export
<img width="624" alt="screen shot 2018-02-08 at 00 36 47" src="https://user-images.githubusercontent.com/11535118/35947438-2f7772b0-0c68-11e8-96f0-39c2b5993a94.png">

So as you can see i lose safety, additionally i lose possibility to quickly fix that issue.

**Comment by MikeMcl** [comment]
Yes, so it's a matter of being able to catch the missing import at compile time or with intellisense.

But if I remove the `declare global` section and create separation declaration files for module and global usage, then that opens a can of worms regarding how easy it is for users to configure the typescript compiler to find the particular declaration file they need.

I suppose I would have the `types` property of this library's *package.json* pointing to the declaration file for module usage, as that is probably wanted more often, but then that may make it difficult for users wanting the other declaration file for global usage...

Any thoughts?


#hit would mean that what would they be named and how would they then be discovered by the typescript compiler? What would I put in the `types` property of this library's *package.json*?

**Comment by pgebheim** [comment]
This definition creates another (major) issue:

The Scenario:
- Project `P` depends on BigNumber6
- Module `M` depends on BigNumber6, and exports typings that use BigNumber
- Module `M` is `npm link` or `yarn link`d into Project `P`

IN this case, there are two copies of `bignumber.d.ts` in the source tree, due to the symlink used by `npm link`.
```
P/node_modules/bignumber.js/bignumber.d.ts
P/node_modules/M/node_modules/bignumber.d.ts
```

`tsc` will then process this typings file as part of the typings for module `M` and again when project `P` imports BigNumber.js

In this case, we get an ERROR from tsc because of the global declarations because we've globally exported n object not a module:

```
node_modules/bignumber.js/bignumber.d.ts(1760,9): error TS2649: Cannot augment module 'BigNumber' with value exports because it resolves to a non-module entity.
```

**Comment by MikeMcl** [comment]
@pgebheim 

I can't make complete sense of your post, but, yes, I agree that it would be better to remove the global stuff from the definitions file, as I did recently with *decimal.js*.

I'll get on it presently.

**Comment by lanthaler** [comment]
+1, this is creating issues for me too

**Comment by thehappycoder** [comment]
I get the same issue as @pgebheim

**Comment by MikeMcl** [comment]
> This doesn't make a lot of sense since if they're using Typescript to get the typings they are by definition in a module-supporting environment. And furthermore, if they're NOT then the typings are totally ignored in any case.

Total nonsense. But anyway, I'll release a new version without the global typings at the end of next week.

**Comment by MikeMcl** [comment]
Removed global BigNumber from typings in *v7.0.0*.

**Comment by dmichael** [comment]
Thanks for correcting this! I just hit the situation where TS compiled happily, but at runtime BigNumber was missing. The update to v7 did the trick.

**Comment by jacksondoherty** [comment]
I believe this issue still exists. Please see Issue #391 which includes a minimal reproducible example via a nextjs hello world app.
