### ISSUE TITLE
toString drops significant bits/digits if it is 0

### ISSUE THREAD

**Issue by D-Nice** [MikeMcl/bignumber.js#149]
As an example, for base16 converison, expecting: 
```js
console.log((new BigNumber(46240771455)).toString(16))
```
to equal: `0ac42a2d7f`
as it does in python's equivalent:
but instead getting: `ac42a2d7f` which is malformed hex/base16, drops off any significant 0.

Same happens with base2, is this working as designed, in which case users are expected to do checks that significant bits aren't dropped, because for example putting the above malformed base16 conversion into a buffer, will cause issues and give incorrect results.

**Comment by D-Nice** [comment]
I presume this is done to follow the native behaviour of toString. Unfortunately I got spoiled there a bit working with python, and expected this library to behave similarly, closing as it's not an issue specific to this library.

**Comment by MikeMcl** [comment]
Python:
```python
hex(46240771455)              # 0xac42a2d7f
format(46240771455, 'x')      # ac42a2d7f
```
