### ISSUE TITLE
Non-registry package missing package.json: bignumber.js

### ISSUE THREAD

**Issue by fccbb** [MikeMcl/bignumber.js#150]
hi there,

I'm trying to install 
$sudo npm install truffle-hdwallet-provider and this is the error message I get:

```json
3 silly saveTree ├── babel-preset-es2017@6.24.1
13 silly saveTree └── babel-register@6.26.0
14 verbose stack Error: Non-registry package missing package.json: bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c$
14 verbose stack     at BB.join (/usr/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:160:23)
14 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
14 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14$
14 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>$
14 verbose stack     at Promise.eval (eval at thenCallback (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
14 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
14 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
14 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
14 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
14 verbose stack     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21)
14 verbose stack     at Object.emit (events.js:185:15)
14 verbose stack     at Object.Parser.on._ (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:75:14)
14 verbose stack     at Object.emit (events.js:180:13)
14 verbose stack     at Object.[emit] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:229:12)
14 verbose stack     at Object.[maybeEnd] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:345:17)
14 verbose stack     at Object.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:353:21)
15 verbose cwd /home/blacksheep/smart-contracts-master
16 verbose Linux 4.15.7-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/sbin/npm" "install" "truffle-hdwallet-provider"
18 verbose node v9.8.0
19 verbose npm  v5.7.1
20 error code ENOPACKAGEJSON
21 error package.json Non-registry package missing package.json: bignumber.js@git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2.
22 error package.json npm can't find a package.json file in your current directory.
23 verbose exit [ 1, true ]
```

Now I tried:

$npm install bignumber

but I get the same message. I'm not yet familiar with npm, I'm trying to work with truffle 

$truffle compile

and the project I am looking at needs truffle-hdwallet-provider to compile. However, I don't understand this error any help would be very appreciated thank you!

I've tried messing with package-lock.json of the truffle project and change the bignumber.js to

https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.js

But it still gives me the error.

% npm -v                                                                                                           
5.7.1

% truffle version                                                                                                       
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)

**Comment by MikeMcl** [comment]
`npm install bignumber.js`

**Comment by fccbb** [comment]
% sudo npm install bignumber.js                                                      :(
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: bignumber.js@https://github.com/debris/bignumber.js/blob/master/bignumber.js.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-11T20_57_07_892Z-debug.log

**Comment by MikeMcl** [comment]
This is not as issue with this library. I have nothing to do with *https://github.com/debris/bignumber.js* or *chai-bignumber*.

**Comment by fccbb** [comment]
sorry mate I thought I was in the right repo thank for your help anyway.
