### ISSUE TITLE
Can bignumber.js round to nearest non-zero decimal value?

### ISSUE THREAD

**Issue by AoDev** [MikeMcl/bignumber.js#151]
Hello,

I am trying to figure out how to round numbers of arbitrary decimal precision.
I am not sure how to formulate this properly in English so here are some examples, that illustrate the problem:

```
roundMe(0.000041281111) -> 0.00004
roundMe(0.000041281111, 2) -> 0.000041
roundMe(0.000041281111, 3) -> 0.0000413
```

Note that the numbers may be very small and I can't use a fixed precision or most of them would just end up being rounded to 0.

If bignumber.js can not do this, would you be open to turn this into a feature request?

**Comment by MikeMcl** [comment]
Hi,

It would have been more appropiate to ask this question on [stackoverflow](https://stackoverflow.com/).

See the rounding methods, [precision](http://mikemcl.github.io/bignumber.js/#sd) and [decimalPlaces](http://mikemcl.github.io/bignumber.js/#dp).

```js
x = new BigNumber('0.000041281111')
x.precision(1)     // '0.00004'
x.precision(2);    // '0.000041'
x.precision(3)     // '0.0000413'
```

**Comment by AoDev** [comment]
@MikeMcl Sorry. I found the `toPrecision` method but missed the `precision` one. Thank you for answering 👍

**Comment by tisnNguyen** [comment]
Hi my name is Tuan from Aura network

**Comment by kyosheek** [comment]
If anyone lands here looking for "bignumber.js rounding", `.precision()` or `.decimalPlaces()` do not modify BigNumber instance in-place as can be seen in [original examples](https://github.com/MikeMcl/bignumber.js/blob/eb6a1f2706cd7457fae5977c2d87df5830a1617f/types.d.ts#L1129) (which is also do not specified in function description)
