### ISSUE TITLE
[discuss] how to convert result from bignumber function to primitive type

### ISSUE THREAD

**Issue by examin** [MikeMcl/bignumber.js#153]
when I use bignumber round function it returns a correct result, but I need a result of the primitive type float or int. so that I can use result with pre-written functions in projects(without use bignumber API). 
Please ask any question if required.  I need a solution soon. Please advice a way so that i can convert the result to float or int type

**Comment by MikeMcl** [comment]
The `toNumber` method wil convert a BigNumber to a primitve JavaScript number.
