### ISSUE TITLE
why pow does NOT support BigNumber when the mod is given.

### ISSUE THREAD

**Issue by xinyuwang** [MikeMcl/bignumber.js#154]
I think modPow is a useful function in crypto, however, BigNumber 's multipliedBy function doesn't support big number even a mod is provided. Any ideas?

**Comment by MikeMcl** [comment]
Yes, this has come up before, see #95.

I agree with you that the `exponentiatedBy` functon should support big numbers and I will implement this when time permits.

**Comment by xinyuwang** [comment]
Thanks a lot.

**Comment by MikeMcl** [comment]
Added support in *v7.0.0*.
