### ISSUE TITLE
isValidBigNumber() static method

### ISSUE THREAD

**Issue by borovik96** [MikeMcl/bignumber.js#155]
`new BigNumber(n)` throws an error if parameter `n` is invalid. To handle case when `n` is invalid parmeter needs to wrap a creating new BN in `try/catch` block

It will be better to have `BigNumber.isValid()` method to check is parameter valid or not

**Comment by MikeMcl** [comment]
Published *v7.0.0* which no longer throws on an invalid value by default; BigNumber `NaN` is returned instead:

```js
let x = new BigNumber('8ty');    // 'NaN'

if (x.isNaN()) console.log('Invalid number!');
```

Now, a `DEBUG` property has to be added to `BigNumber` and set to `true`, for an error to be thrown:

```js
let x = new BigNumber('8ty');    // '[BigNumber Error] Not a number: 8ty'
```
