### ISSUE TITLE
Global object variable name typo

### ISSUE THREAD

**Issue by art-bazhin** [MikeMcl/bignumber.js#158]
https://github.com/MikeMcl/bignumber.js/blob/5d31744b0ca64d64c47ad824b449a4cf386f38f8/bignumber.js#L2799

Probably `globalScope` should be `globalObject`.

**Comment by MikeMcl** [comment]
Thanks a lot! Such things always seem to happen when I publish a new major version - I immediately have to re-publish.

Fixed in *v7.0.1*.

**Comment by devinus** [comment]
@MikeMcl will this be pushed to npm soon? A lot of people use npm now for even browser deps, e.g. webpack.

**Comment by MikeMcl** [comment]
@devinus 

Yes, I published to npm straight away.
