### ISSUE TITLE
Issues in type definition

### ISSUE THREAD

**Issue by k102-wings** [MikeMcl/bignumber.js#160]
Found some issues when using type script:

`TS2339: Property 'shift' does not exist on type 'BigNumber'`
`TS2339: Property 'floor' does not exist on type 'BigNumber'`
`TS2339: Property 'mul' does not exist on type 'BigNumber'`

Can we have them in bignumber.d.ts?

**Comment by MikeMcl** [comment]
Those methods are from *v5.0.0*. See the definitions file for that version.

```bash
npm install bignumber.js@5.0.0
```

The current *bignumber.d.ts* applies to *v6.0.0+* only.

**Comment by k102-wings** [comment]
Thanks for your help!
