### ISSUE TITLE
Discussion of "has more than 15 significant digits" continued

### ISSUE THREAD

**Issue by fresheneesz** [MikeMcl/bignumber.js#161]
@MikeMcl Since you [locked the other issue](https://github.com/MikeMcl/bignumber.js/issues/148#issuecomment-378970347), I'm responding to your comment to me here.

> 9.99991111e+25 .. is a number with 9 significant digits

I agree.

> 99999111100000000000 .. [is] a number with 20 significant digits

That's not correct. If you look up [the definition of significant digits](https://en.wikipedia.org/wiki/Significant_figures), you'll see that 99999111100000000000 also has 9 significant digits, not 20. All those trailing zeros are **not** significant digits. So this is another reason why that error message is confusing, because its using that phrase incorrectly.

**Comment by MikeMcl** [comment]
Did you actually read the Wikipedia article you link to?

> "In a number without a decimal point, trailing zeros may or may not be significant..."
> "The significance of trailing zeros in a number not containing a decimal point can be ambiguous... it is often necessary to determine from context whether such trailing zeros are intended to be significant."

The context is whether to warn a user that precision may have been lost. 

```
console.log(99999111100000000001)      // '99999111100000000000'
console.log(99999111100000000000.5)    // '99999111100000000000'

// 99999111099999999999  Error: number type has more than 15 significant digits
// 99999111100000000000  Why so different?
// 99999111100000000001  Error: number type has more than 15 significant digits
// 99999111100000000002  Error: number type has more than 15 significant digits
```

If I lock an issue it means I am not interested in continuing the discussion. Please respect that.

Your time would be better spent learning about how JavaScrpt numbers are implemented, not trying to argue about significant digits.

**Comment by fresheneesz** [comment]
I'll stop wasting both our time because it seems you don't really care that your error messages are confusing people.
