### ISSUE TITLE
PhysicsEngine

### ISSUE THREAD

**Issue by whaqzhzd** [MikeMcl/bignumber.js#163]
I am a js game developer and I am developing a physical module based on frame synchronization. I need this module to ensure consistent input and consistent output on each client. So I need to implement a fixed-point module. Because floating point numbers can cause errors, resulting in consistent input, the output can be inconsistent. Fortunately, I saw bignumber.js. I don't know if it's satisfying my needs. If I use bignumber as the underlying Number type, implement the physics engine. Is it possible to ensure consistent input and consistent output? On different CPUs.

**Comment by josdejong** [comment]
I'm not sure whether bignumber.js is deterministic on all different JS engines.

You may want to have a look at https://github.com/stdlib-js/stdlib though, I think having consistent output for basic math functions is one of the goals.

**Comment by whaqzhzd** [comment]
Thank you for your help

**Comment by MikeMcl** [comment]
> Because floating point numbers can cause errors, resulting in consistent input, the output can be inconsistent.

If you are referring to results like
```js
0.1 + 0.2    // 0.30000000000000004
```
then can't you just stick to integers - you have `9007199254740991` of them to work with, surely that's enough! 

The CPU should be irrelevant to this library's output, but for a physic's engine you would surely want to stick to primitive numbers for performance reasons.

What inconsistencies are you talking about exactly anyway?

**Comment by MikeMcl** [comment]
The results from the `Math` object's methods may not be excatly the same on all platforms, but arithmetic with the JavaScript number type should be consistent everywhere. If you have an example of it not being so I would like to see it.

**Comment by whaqzhzd** [comment]
Thank you, for the precision caused by the float, I just checked the relevant documents on google, but I think the basic data type of js is the precision under the strict IE754 standard. Theoretically, there will be no such problem. If only the result of the math object will cause this problem, the addition and subtraction multipliers and logical judgments (equal, greater than or less than) for javascript's basic data types are the same principle. We only need to implement the floor, ceil, cos, abs Sin and so on function library can achieve the consistent input consistent output I want.

**Comment by cwellsx** [comment]
> We only need to implement the floor, ceil, cos, abs Sin and so on function library can achieve the consistent input consistent output I want.

I understand why the result of functions like `cos` might differ across platforms or libraries -- e.g. their implementations may have different time/accuracy trade-offs. But, why do think that `floor` and `ceil` might be uncertain in practice (assuming it's true that JavaScript using IEEE 754)?
