### ISSUE TITLE
Missing Zero in coefficient

### ISSUE THREAD

**Issue by jricaldi** [MikeMcl/bignumber.js#164]
I am working in a factorial problem using BigNumber.js, if n = 20 the result should be
`2432902008176640000` (19 characters)
but instead of that the coefficient is like this:
 `BigNumber { s: 1, e: 18, c: [ 24329, 2008176640000 ] } `
There is a missing zero in `c[1]`
Somebody could help me, please? 🙏

**Comment by MikeMcl** [comment]
Nothing is missing, you are misunderstanding how the value is stored.
`c[1]` is effectively `02008176640000`; the leading zero is not shown.
The `toString` value is correct, is it not?
