### ISSUE TITLE
BigNumber not adding or subtracting 

### ISSUE THREAD

**Issue by bigboss88** [MikeMcl/bignumber.js#167]
Hello I'm using BigNumber to help query an ethereum block chain.

I'm trying to use it to keep track of an accounts spending over a period of time

When I go to I try to add or subtract my total, which is a BigNumber, the value doesn't change 

for example 

```
`var total = new BigNumber(0,10);

total.plus(10)

console.log(total.toString())`
```

returns 0 when it should return 10

**Comment by akostiv** [comment]
`plus` method returns a new instance of `BigNumber` that is the sum of the current value and argument. It doesn't mutate the current value.

**Comment by MikeMcl** [comment]
Yes, so use

`total = total.plus(10);`
