### ISSUE TITLE
Line 1381 - 'break out'

### ISSUE THREAD

**Issue by tamaramack** [MikeMcl/bignumber.js#168]
https://github.com/MikeMcl/bignumber.js/blob/38ba62a15c0088ca401f1e3bbd5bdb7acf220fe9/bignumber.js#L1381

This line breaks bundling builds on .NET
Line 1381 `break out`

Is there a specific purpose for `out` outside of javascript?

**Comment by MikeMcl** [comment]
By "breaks", do you mean "produces a warning"?

No bundler worth using should break because of a perfectly legitimate `break` to [label](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/break) statement.

**Comment by tamaramack** [comment]
Agreed, your 'label' is legitimate however build fails with .NET build on minification which only identifies `break` within loops. Unfortunately, we are unable to modify the current setup.  Thank you, we will look for alternatives.
