### ISSUE TITLE
Will there be a `square` method?

### ISSUE THREAD

**Issue by rodoabad** [MikeMcl/bignumber.js#169]
Currently there is only `squareRoot` which is `1/2`. Will there be a `square` method in the future so I can pass in `1/x` where `x` is an Integer?

Right now `exponentiatedBy` only accepts Integers so I cannot pass `(1/5)` or `0.2` which is also the same as the square of `1/5`.

Another alternative is using vanilla `Math.pow(x, (1/5))`.

Thanks!

**Comment by MikeMcl** [comment]
Are you thinking of an `nthroot` method? So the square root would be `x.nthroot(2)` and the cube root would be `x.nthroot(3)` etc. 

I have considered it before, but nothing came of it, and I am unlikely to add it here in the forseeable future. There may be an implementation of it somewhere in the issues or pull requests for this library or *decimal.js*.

The [decimal.js](https://github.com/MikeMcl/decimal.js) power operation accepts exponents that are not integers.
