### ISSUE TITLE
A noConflict method

### ISSUE THREAD

**Issue by Xotic750** [MikeMcl/bignumber.js#17]
Would it be possible to have a noConflict method for BigNumber. This would allow me to have a private BigNumber object for use in my library, where I set specific config() options. And it would allow the user to have a global BigNumber where they can have different config() options that will not affect my private copy. I know that using RequireJS or NodeJS will do this for me, but I'm a little stuck with the case where BigNumber is injected or loaded with `<script>` Or perhaps there is a better way?

**Comment by Xotic750** [comment]
Like what you have done there, however, for my application I need precision to work with decimal places and not significant figures. Have you had any further thoughts of adding a factory method to BigNumber?

**Comment by MikeMcl** [comment]
I added it to [big.js](http://mikemcl.github.io/big.js/#faq) not long ago, so perhaps you could use that if you want to work with decimal places. 

To create a fresh constructor in decimal.js:

    D = Decimal.constructor();

And in big.js:

    B = Big();

In bignumber.js? Not sure...

I'll consider it further, but I updated bignumber.js just recently, so I'd prefer not to look at that code again for a few months...

**Comment by Xotic750** [comment]
I'll have a closer look at Big and see if that handles everything I need.

**Comment by Xotic750** [comment]
So, there is no `.config` in big.js other than editing the file itself? Because I need to set dp and rounding mode and stuff.

**Comment by MikeMcl** [comment]
No NaN and Infinity, but decimal places and rounding mode can be set using, for example

    Big.DP = 20;
    BIg.RM = 1;

**Comment by Xotic750** [comment]
Aha, thanks for the `config` info. Don't think I can do without the NaN etc support though.
