### ISSUE TITLE
Start to think about ECMAscript BigInt's

### ISSUE THREAD

**Issue by hildjj** [MikeMcl/bignumber.js#175]
See https://tc39.github.io/proposal-bigint

Some possibilities
- add ToBigInt()
- more explicit BigInt support in the constructor.  They work now by going through a decimal string conversion and parse
- if native BigInt's get really fast, it might make sense to use them in some cases in the implementation, even given the explosion in complexity that might cause.

**Comment by lidel** [comment]
Relevant news: [Firefox 68 shipped support for `BigInt`](https://hacks.mozilla.org/2019/07/firefox-68-bigints-contrast-checks-and-the-quantumbar/).
This means both Chromium 67+ and Firefox 68+ now support it.

**Comment by prasannavl** [comment]
Adding to the above, also there in Node 12+ (Currently LTS)

**Comment by hildjj** [comment]
Instead of opening a new issue, I thought it might be right to add "start to think about BigDecimal" here as well.  TC39 is just starting to think about this, see https://github.com/tc39/proposal-decimal for more info.

If nothing else, ensuring that the experience that this implementation has gained is reflected in the discussion there is likely important.  It would also be nice to be able to use this implementation as a polyfill for the non-syntactic parts.

**Comment by rodoabad** [comment]
Any updates on this? Should we start moving towards `BigInt`?

**Comment by MikeMcl** [comment]
@rodoabad Nothing to report at this time.
