### ISSUE TITLE
Pass custom formatting options to `toFormat` method

### ISSUE THREAD

**Issue by akostiv** [MikeMcl/bignumber.js#178]
Can `toFormat` method be extended to accept custom format?
For instance: `toFormat(dp , rm, format)` where format has the same properties as `FORMAT` from config.

Thanks!

**Comment by Argun** [comment]
I use the below solution,

`export function format(params, hash) {
  let scale = 0;
  let v = params[0];
  let format = {
    groupSize: 3,
    fractionGroupSize: 0,
    groupSeparator: ',',
    decimalSeparator: '.',
    secondaryGroupSize: 0,
    fractionGroupSeparator: ' '
  };

  if (hash && hash.scale) {
    scale = hash.scale;
  }
  
  if (hash && hash.groupSeparator) {
    format.groupSeparator = hash.groupSeparator;
  }

  BigNumber.config({ FORMAT: format });
  return new BigNumber(v).toFormat(scale);

}`

**Comment by Argun** [comment]
I use the below solution.

`export function bigNumber(params, hash) {
  let scale = 0;
  let v = params[0];
  let format = {
    groupSize: 3,
    fractionGroupSize: 0,
    groupSeparator: ',',
    decimalSeparator: '.',
    secondaryGroupSize: 0,
    fractionGroupSeparator: ' '
  };

  if (hash && hash.scale) {
    scale = hash.scale;
  }

  if (hash && hash.groupSeparator) {
    format.groupSeparator = hash.groupSeparator;
  }

  BigNumber.config({ FORMAT: format });
  return new BigNumber(v).toFormat(scale);

}`

**Comment by Argun** [comment]
I use the below solution.

```
export function bigNumber(params, hash) {
  let scale = 0;
  let v = params[0];
  let format = {
    groupSize: 3,
    fractionGroupSize: 0,
    groupSeparator: ',',
    decimalSeparator: '.',
    secondaryGroupSize: 0,
    fractionGroupSeparator: ' '
  };

  if (hash && hash.scale) {
    scale = hash.scale;
  }

  if (hash && hash.groupSeparator) {
    format.groupSeparator = hash.groupSeparator;
  }

  BigNumber.config({ FORMAT: format });
  return new BigNumber(v).toFormat(scale);

}
```

**Comment by max7z** [comment]
@Argun I'm not sure that your solutions is safe. As I understand, there is a global setting for it. If I have  BigNumber.config({ FORMAT: format }); somewhere in my code, your function can change my previous formatting.

**Comment by DmitryGG** [comment]
+1. Why we have global config and have no way to config instances?

**Comment by MikeMcl** [comment]
The following allows a format object to be passed as the first parameter to `toFormat`, and also a format object to be added per instance as a `format` property:

```js
BigNumber.prototype.toFormat = (function () {
  const toFormat = BigNumber.prototype.toFormat;
  return function (format, dp, rm) {
    if (format && typeof format == 'object' ||
      (rm = dp, dp = format, format = this.format)) {
      const defaultFormat = BigNumber.config().FORMAT;
      BigNumber.config({FORMAT: format});
      let result = toFormat.call(this, dp, rm);
      BigNumber.config({FORMAT: defaultFormat});
      return result;
    } 
    return toFormat.call(this, dp, rm);
  };
})();
```

**Comment by MikeMcl** [comment]
From *v8.0.0*, `toFormat` will accept an object of formatting options as the first, second or third parameter.
Also added `prefix` and `suffix` options.

```javascript
// Method signatures
toFormat(dp, rm, format)
toFormat(dp, format)
toFormat(dp, rm) 
toFormat(format)
toFormat(dp)
toFormat() 
```
