### ISSUE TITLE
toFixed discrepancy 

### ISSUE THREAD

**Issue by TechedImpala** [MikeMcl/bignumber.js#181]
Hi,

First of, this is an amazing lib....

The discrepancy I am facing is when I use toFixed:

 let p = new BigNumber("110.89021291125").toFixed(2,0); : this gives 110.90
 let p = new BigNumber("110.890").toFixed(2,0); : this gives 110.89

Am I missing something obvious?

Thanks in advance

**Comment by OussamaRomdhane** [comment]
That's a normal behavior for `.toFixed`, the method rounds the decimal places before before "cropping" it.
http://mikemcl.github.io/bignumber.js/#toFix

The second parameter is the rounding mode (see http://mikemcl.github.io/bignumber.js/#constructor-properties) and your result will veries depending on the chosen rounding mode

To obtain the same behavior as JS try 
```javascript
new BigNumber("110.89021291125").toFixed(2); 
``` 
This will work unless you have overriden the rounding mode for BigNumber doing something like this 
```javascript
BigNumber.config({ ROUNDING_MODE: 0 });
 ```

**Comment by TechedImpala** [comment]
@MangooID 
Thank you very much, will now be using rounding mode 4 rather than 0.

**Comment by OussamaRomdhane** [comment]
👍 

Just FYI the default rounding mode is 4

https://mikemcl.github.io/bignumber.js/#rounding-mode
