### ISSUE TITLE
crypto is not defined

### ISSUE THREAD

**Issue by gorgos** [MikeMcl/bignumber.js#183]
I see that in https://github.com/MikeMcl/bignumber.js/commit/4a80c3637245606279eda45e503a428b8f9b9793, you removed the `var crypto = require('crypto')`.

In NodeJS I need that, otherwise it throws an error that `crypto` is not defined.

**Comment by MikeMcl** [comment]
Yes, I moved the responsibility for providing the `crypto` object to the user:

```js
global.crypto = require('crypto')
```

I will make this explicit in the documentation.

**Comment by MikeMcl** [comment]
Added to the documentation in *v8.0.0*.
Thanks for the report.
