### ISSUE TITLE
toFraction sometimes returns a string which does not represent an integer

### ISSUE THREAD

**Issue by barakman** [MikeMcl/bignumber.js#184]
Example:

    let x = new BigNumber("234.61938355185511345991");
    let [n, d] = x.toFraction();
    console.log(n); // 2.3461938355185511345991e+22
    console.log(d); // 100000000000000000000

It might be better to have this function returning `[BigNumber, BigNumber]` instead of `[string, string]`.

Version tested: 7.2.1.

**Comment by MikeMcl** [comment]
Yes, I made that change in *decimal.js*.

Your preference is noted.

**Comment by barakman** [comment]
@MikeMcl:

Alternatively, you could change this:
```
          ? [n1.toString(), d1.toString()]
          : [n0.toString(), d0.toString()];
```
To this:
```
          ? [n1.toFixed(), d1.toFixed()]
          : [n0.toFixed(), d0.toFixed()];
```
I think that will ensure returning an integer-representing string.

**Comment by MikeMcl** [comment]
Yes, good idea. I will consider it.

**Comment by MikeMcl** [comment]
From *v8.0.0*, `toFraction` returns `[BigNumber, BigNumber]`.
Thanks for your input.
