### ISSUE TITLE
Safety option to prevent accidental addition to string

### ISSUE THREAD

**Issue by joeytwiddle** [MikeMcl/bignumber.js#185]
An issue was raised here when somebody accidentally used `+` on a BigNumber.

https://github.com/ethereum/web3.js/issues/858

Would it be possible to add an option to the BigNumber library, e.g. `{paranoid: true}` which would throw an Error if `valueOf` was called.

The goal is to protect developers from accidentally treating a BigNumber as if it was a normal number.

**Comment by MikeMcl** [comment]
I will consider it, though it will be another month or so before I am able to work on this library again.

**Comment by MikeMcl** [comment]
I've decided against this. If you want to throw on `valueOf`, all that is required is:

```javascript
BigNumber.prototype.valueOf = function () {
  throw Error('valueOf called on a BigNumber instance!');
};
```

Though that would cause the `toNumber` method to throw, unless it was redefined:

```javascript
BigNumber.prototype.toNumber = function () {
  // toJSON references the original valueOf function
  return Number(this.toJSON());
};

Of course, to get a number primitive from a BigNumber you could also just use `Number(x.toString())`, but that would return `0` for a BigNumber with value `-0`.

**Comment by MikeMcl** [comment]
Actually, the `exponentiatedBy` / `pow` method calls `valueOf` internally when the BigNumber it is called upon hs the value `0`, `1`, `NaN` or `Infinity`, so it will throw if using the solution I posted above.

I will remove this `valueOf` call presently so the above solution does work.

**Comment by MikeMcl** [comment]
From *v8.0.0*, but not before, you can just do:

```javascript
BigNumber.prototype.valueOf = function () {
  throw Error('valueOf called on a BigNumber instance!');
};
```

See [Type coercion](http://mikemcl.github.io/bignumber.js/#type-coercion).
