### ISSUE TITLE
BigNumber prototype should have util.inspect.custom for NodeJS

### ISSUE THREAD

**Issue by Recmo** [MikeMcl/bignumber.js#188]
Currently `console.log(new BigNumber(42))` outputs the following in NodeJS:

```
BigNumber { s: 1, e: 1, c: [ 42 ] }
```

Ideally it should output `42`. This can be solved by setting `util.inspect.custom` on BigNumber.prototype. Users can patch it as follows (in TypeScript):

```ts
import { BigNumber } from 'bignumber.js';

// Set a debug print function for NodeJS
import isNode = require('detect-node');
if (isNode) {
    // Dynamically load a NodeJS specific module.
    // Typescript requires all imports to be global, so we need to use
    // `const` here and disable the tslint warning.
    // tslint:disable-next-line: no-var-requires
    const util = require('util');

    // Set a custom util.inspect function
    (BigNumber.prototype as any)[util.inspect.custom] = function(): string {
        // Return the readable string representation
        // tslint:disable-next-line: no-invalid-this
        return this.toString();
    };
}
```

**Comment by MikeMcl** [comment]
Thanks for the information. 
I won't add this to the library though as I don't want to include any `require` calls.

**Comment by MikeMcl** [comment]
Added note to *README* regarding `util.inspect.custom`, and added custom inspect function internally for users of Node.js *v10.12.0+*.

Thanks for your input.
