### ISSUE TITLE
Function isPositive returns true for 0

### ISSUE THREAD

**Issue by barakman** [MikeMcl/bignumber.js#194]
IMO, this is either a bug, or a very misleading function-naming.

Here is a simple way to reproduce:
```
let x = new BigNumber(0);
console.log(x.isPositive());
```

According to [the documentation of the function](https://mikemcl.github.io/bignumber.js/#isPos), it is indeed a bug:
> Returns `true` if the value of this `BigNumber` is positive, otherwise returns `false`.

That is, unless you change the word `value` to `sign`.
But even then, the function name will remain extremely misleading (I just spent a very long time debugging my code until realizing that this seemingly-simple function was returning the opposite of what I was expecting it to).

The same problem may occur with function `isNegative` returning `true` for a zero value.

I suggest to keep the documentation as is, and update the implementation of these two functions to verify that the number is not zero.

For example:
```
    P.isPositive = function () {
      return this.s > 0 && !this.isZero();
    };
```

Thanks

**Comment by MikeMcl** [comment]
Changed the word "value" to "sign" in v8.0.0.

**Comment by Malabarba** [comment]
Hi there. First of all, thanks for all the effort that went into this package.

I understand that you can have a bignum `0` with a positive or negative sign.
Still, I just wanted to pitch in here to say that `(new BigNumber(0)).isPositive()` returning true was a very unexpected behavior for me. Although it is working *as documented*, anywhere I look I would expect `x.isPositive()` to behave like `x > 0`.

Not saying you should change how the function works (it's probably too late for that), do what you feel is best.
