### ISSUE TITLE
API consistency between bignumber.js and decimal.js

### ISSUE THREAD

**Issue by barakman** [MikeMcl/bignumber.js#195]
Since you are the author of both projects, I think it might be very useful to align their APIs as much as possible.

This way, one can easily switch between the two classes when needed.

It seems that they are mostly aligned with each others, but there are nevertheless some inconsistencies.

For example: `BigNumber.isGreaterThan` vs `Decimal.greaterThan`.

Thanks

**Comment by MikeMcl** [comment]
I consider the *bignumber.js* API to be in its final form at this point. 
 
I may make changes to *decimal.js* to align it more with this library, such as having all methods that return a boolean start with `is`, but API changes can be difficult, see, for example, #139.

**Comment by barakman** [comment]
@MikeMcl:
I find both packages to be extremely useful, and have just moved to bignumber v8.0.0.
Thank you.
