### ISSUE TITLE
How to get decimal parts of a number?

### ISSUE THREAD

**Issue by victor192** [MikeMcl/bignumber.js#196]
For example, I have a big number:
```
const str = "0.221410676794694825"
const number = new BigNumber(str)
```
I need to get an array of two elements - an integer part and a decimal, that is: `["0", "221410676794694825"]`. Is there such a possibility in your library?

**Comment by arguiot** [comment]
You can do `number.toString().split(".")`

**Comment by victor192** [comment]
Thank you, useful thing. Can be closed issue.
