### ISSUE TITLE
Bitwise operators

### ISSUE THREAD

**Issue by ashrafsabrym** [MikeMcl/bignumber.js#2]
Greetings,

Is there any plans to implement bitwise operators?
[This library](http://www.leemon.com/crypto/BigInt.js) implements them, but it's messy and may not be reliable.

**Comment by noorfathima11** [comment]
Implementing bitwise operations is essential since BigInt has it, but for many purposes where exponents may be considered switching between BigNumber and BigInt is resource heavy.
