### ISSUE TITLE
Error export when run tests

### ISSUE THREAD

**Issue by totaki** [MikeMcl/bignumber.js#200]
React 15, default environment
![2018-10-07 23-50-44](https://user-images.githubusercontent.com/6254062/46586772-d5bd0680-ca8b-11e8-951f-c1374309efb2.png)

**Comment by MikeMcl** [comment]
The `export var BigNumber = clone();` is from *bignumber.mjs*. Does Jest support modules?

This is an [issue with Jest](https://github.com/facebook/jest/issues/4842) and its configuration. Perhaps try asking a question on [stackoverflow](https://stackoverflow.com/).
