### ISSUE TITLE
Recent changes to bignumber.d.ts are incorrect

### ISSUE THREAD

**Issue by sandersn** [MikeMcl/bignumber.js#203]
0280915d3c04859358455b41b78315ec682e5a73 made a number of changes to bignumber.d.ts. Specifically, it deleted all the `[]` from the end of rest parameters:

```diff
   * @param n A numeric value.
   */
-  static minimum(...n: BigNumber.Value[]): BigNumber;
+  static minimum(...n: BigNumber.Value): BigNumber;

```

However, the `[]` is required, so bignumber.d.ts doesn't actually compile anymore.

**Comment by MikeMcl** [comment]
Yes, that was a mistake. Fixed in *v8.0.1*.
