### ISSUE TITLE
new BigNumber(4236506602079137).times(4).plus(181)

### ISSUE THREAD

**Issue by jacktang** [MikeMcl/bignumber.js#208]
* the version: "bignumber.js": "^8.0.1"
* 4236506602079137 * 4 + 181 = 16946026408316729, not 16946026408316728

**Comment by MikeMcl** [comment]
Is this spam?
If not, please explain what the problem is.

**Comment by MikeMcl** [comment]
The answer of 16946026408316729 given by this library is correct.

**Comment by MikeMcl** [comment]
The answer of 16946026408316729 given by this library is correct.
JavaScript numbers have limited precision.
