### ISSUE TITLE
div function Browser crash

### ISSUE THREAD

**Issue by 372572571** [MikeMcl/bignumber.js#210]
I am in weixin game project. use div function.  Will cause a crash .
As long as I don't use it, it won't happen

**Comment by MikeMcl** [comment]
Are you using iOS 10.3 or similar by any chance? It may be related to [this](https://github.com/MikeMcl/bignumber.js/issues/120) bug in some older versions of *JavaScriptCore* on iOS.

Does including the following code before loading *bignumber.js* fix the issue?

```js
if (Object.keys({'250': 0.5, '1000': 0.1}).length !== 2) {
  Array.prototype.unshift = function () {
    Array.prototype.splice.apply(this, Array.prototype.concat.apply([0, 0], arguments));
    return this.length;
  };
  Array.prototype.shift = function () {
    return Array.prototype.splice.call(this, 0, 1)[0];
  };
}
```

**Comment by 372572571** [comment]
I tried to make it . But the effect is regrettable.
I used your Decimal.js. Make my game complete
