### ISSUE TITLE
Wrong results for multiplications

### ISSUE THREAD

**Issue by tilor** [MikeMcl/bignumber.js#215]
Hi,

I´m trying to use BigNumber for a financial application. However  I have problems with the precision of results:

    x = new BigNumber(47187.8792)
    x.times(74.17)    // 3499925.000264

This happens with many calculations, so I guess I'm missing something?

**Comment by MikeMcl** [comment]
The answer of 3499925.000264 is correct. What is your problem, sunshine?

**Comment by tilor** [comment]
The dataset I'm validating, Excel as well as my Casio pocket calculator all returned 3499925 - but you are correct, BigNumber is more precise than those...
Chapeau and thanks a lot for providing such a great library!
