### ISSUE TITLE
toNumber is not identical to unary operator

### ISSUE THREAD

**Issue by e-x-wilson** [MikeMcl/bignumber.js#218]
The docs say "This method is identical to using type coercion with the unary plus operator." at http://mikemcl.github.io/bignumber.js/#toN

The method returns `NaN` instead of `0` when used with an empty string

<img width="313" alt="screen shot 2019-01-30 at 1 36 32 pm" src="https://user-images.githubusercontent.com/31283824/52007518-37b6d700-2494-11e9-9ac8-28ecbcef0ee8.png">

**Comment by baer** [comment]
The implementation in BigNumber seems like the correct behavior for a math lib. Maybe the right fix is to change the documentation.

**Comment by MikeMcl** [comment]
The documentation is correct in this respect.

You are not calling `toNumber` on an empty string, you are calling it on a BigNumber with the value `NaN`.

```js
x = new BigNumber("");
x.toString()    // "NaN"
x.toNumber()    // NaN
+NaN            // NaN
```

**Comment by MikeMcl** [comment]
No, I don't think that is necessary, thank you, Eric. I have plenty to do addressing real issues.
