### ISSUE TITLE
Handling Repeating decimal

### ISSUE THREAD

**Issue by upupming** [MikeMcl/bignumber.js#225]
Hi, this is a noob question, you can see the result:

```js
let a = new BigNumber(1).dividedBy(3);
let b = a.multipliedBy(3);
console.log(b);
console.log(b.isEqualTo(new BigNumber(1)));
// 0.99999999999999999999
// false
```

Is it possible to make the value of `b` be `1` instead of `0.99999999999999999999`.

I just want to compare two big numbers, but I always got `false` when there is repeating decimal during the calculation.

**Comment by MikeMcl** [comment]
You just need to round the result before you make the comparison. For example,

```js
d = b.decimalPlaces(10);
d = b.decimalPlaces(10);
d = b.decimalPlaces(10);
d = b.decimalPlaces(10);
```

console.log(b.isEqualTo(1));    // true
```

**Comment by MikeMcl** [comment]
You just need to round the result before you make the comparison. For example, here are three different ways of rounding a BigNumber:

```js
x = b.decimalPlaces(10);
y = b.precision(10);
z = b.integerValue();
x.isEqualTo(1) && y.isEqualTo(1) && z.isEqualTo(1);    // true
```

**Comment by upupming** [comment]
thanks for your explanation.
