### ISSUE TITLE
Any chance of getting a Qml version of this?

### ISSUE THREAD

**Issue by Light-Wizzard** [MikeMcl/bignumber.js#227]
I could not get this to work using Qml, I think it is because of the way the object is created.

**Comment by MikeMcl** [comment]
Does it work if you move
```js
var BigNumber,
```
to the top of the file?

In detail:

Put
```js
var BigNumber;
```
right at the top of the *bignumber.js* file, and at line 52, change

```js
var BigNumber,
    isNumeric = /^-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i,
```
to
```js
var isNumeric = /^-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i,
```

**Comment by Light-Wizzard** [comment]
I think you would have to create a Qt Qml project and try it, I can get it work somewhat, but I had to make a lot of changes, the line above was one of them, I need to put all vars on separate lines, after that I could create an object, I cleaned up more things that Qt complained about, but did not fix all of them, but once I tried to add a function to it like multiply, it failed, its like it does not see it. 

I ran into another issue with using it, I was able to cut the functions out and get them to work, what I found was that at some point you have to math, and that math is correct, but JavaScript's Floating Point Math trashes it, and I could not get around that. I am working at doing this in boost now, I think JavaScript is not the tool for this job, you send it to a console with no problems, but in use it is always wrong, and it is just not JavaScript, C++ came up with numbers that were even farther off, making JavaScript more accurate than C++ natively. Qml JavaScript is more demanding than Web Engine, it does more checks than just lint, so unless you are into Qt Qml, you can just ignore this, at first I though it would work, now I just do not feel like putting in any more work into trying to get it to work, unless you can find a way to not just any Floating Point to get this result, it will always be off using JavaScript or C++, boost uses gmp_float, I did not look at the code, not sure how they got around dividing, because C++ has the same issue as JavaScript, if it converts to an exponent, it loses precision.

I did see results from BigInt that were correct, but I could not figure out how to get it to work in Qml, it does not use the same JavaScript Engine as the Web.

Great work by the way, I did look at the code and tried to get it to work, it has no issues with Function calls, but not wrapped into an Object, it does not play nice with "this", a known issue.

**Comment by Light-Wizzard** [comment]
I found these documents for JavaScript for Qt
https://wiki.qt.io/JavaScript

Not sure if it has the answers,  I did try the above, 
in my Qml JavaScript I do this:

```
.import "bignumber.js" as BigNumber;
sa="1234.1234";
sb="123456.123456";
var a = new BigNumber(sa);
var b = new BigNumber(sb);
a.multipliedBy(b);
console.debug("a=" + a)

```
I get 1234.1234, so it does set the value, but multipliedBy does not work, 
nor does the dot intellisense operator, as if it does not see any functions in a,
but I do see stuff when using the dot intellisense operator on BigNumber,
so it seems that Qml JavaScript is not seeing the functions.

**Comment by Light-Wizzard** [comment]
Reading the above JavaScript link, I found this:

Qt has been supporting a JavaScript engine compatible with ECMAScript-262 

I also tried the bignumber.mjs version, I had to comment out the exports at the end of the file, then it ran, same results as the bignumber.js, but this seems like a better place to start, I take it this is an older version of the Engine, but I get error:

bignumber.js:2746: ReferenceError: Symbol is not defined

Pointing to this line:

P[Symbol.toStringTag] = 'BigNumber';

```
.import "bignumber.js" as BigNumberJs;
var BigNumber = BigNumberJs.clone({ DECIMAL_PLACES: 10 });
let x = new BigNumber(varValue);
console.debug("x=" + x)
```

**Comment by MikeMcl** [comment]
I've had a look at this, and no alterations to the *bignumber.js* file are needed at all - it just works.

*main.qml:*

```qml
import QtQuick 2.9
import QtQuick.Window 2.2
import "bignumber.js" as Bignumberjs

Window {
    visible: true
    width: 640
    height: 480

    Text {
        id: text1
        font.pointSize: 20
        anchors.centerIn: parent
        text: ""
    }

    function startup() {
        var a = new BigNumber(1);
        var b = new BigNumber(3);
        var result = a.dividedBy(b);
        text1.text = result.toString();
    }

    Component.onCompleted: startup();
}
```

The `BigNumber` function will be added to the QML global scope when the *bignumber.js* file is executed, so it is important not to shadow it by using `import "bignumber.js" as BigNumber`.

**Comment by Light-Wizzard** [comment]
I did verify this, it works, so it is because I am calling this from inside another JavaScript as:

.import "bignumber.js" as Bignumberjs

and that is creating a different type of object, 
so that problem solved, you just can not use this from inside another JavaScript,
so all the JavaScript using it, must be inside the qml,
and that will work, just never thought of doing it that way,
I normally like to separate JavaScript in a separate file,
and it never occurred to me this would not work otherwise,
I found commended out code in the qml where I tested out a different library,
and could not get it to work, 
so I must have concluded it did not matter,
I was wrong, sorry about all the fuse.

Thanks.

**Comment by Light-Wizzard** [comment]
Thanks for pointing that out, I now understand this, I got confused about namespace and global scope when importing, and stepped on the function call, I got to use to C++ calling protocol, that I forgot about JavaScript's.

**Comment by MikeMcl** [comment]
The global `BigNumber` function *is* available inside other JavaScript scipts, for example: 

*other.js:*
```qml
.import "bignumber.js" as Unused

console.log(new BigNumber(1).div(3).toExponential());    // 3.3333333333333333333e-1
```

**Comment by Light-Wizzard** [comment]
A lesson I learned the hard way... 

This is the first App I have written in Qml, I have played with it since it came out, but never actually wrote a whole program with it, so this is a learning experience, now I can finish my Calculator, I knew it had to be something I was doing wrong, I just could not find any examples, I did figure out that you can do Unused.BigNumber, and that works fine, so Unused does not need to be Unused, but as I found out, the Name does matter, and it cannot be the same as Prototype, but can be the same name as a C++ Class, so go figure, thanks for all the help, this Library is great.
