### ISSUE TITLE
Can't manage to get bignumber.js to behave, unknown repair?

### ISSUE THREAD

**Issue by PowerUser1234** [MikeMcl/bignumber.js#228]
Dear Michael,

I am encountering problems trying to get you Javacript 'bignumber.js'
library to work in a web page loaded by 64 bit Firefox 66.02.

I have used the file 'bignumber.js' entirely on its own, away
from any of the download files.  I then have that in the same
directory as my .html file, Rotate.html.
The code involved is right at the end of my Rotate.html file.

I am getting an error that I do not understand.  How
can I have your library work seamlessly?

These should be renamed Rotate.html and bignumber.js:

[Rotate.txt](https://github.com/MikeMcl/bignumber.js/files/3026187/Rotate.txt)
[bignumber.txt](https://github.com/MikeMcl/bignumber.js/files/3026188/bignumber.txt)

By the way, I have heard that your library
"only works at the block level".  Is this true,
and does it impact my problem?  Are there
restrictions about where your BigNumber
objects can and cannot be invocated?

**Comment by MikeMcl** [comment]
> How can I have your library work seamlessly?

A good start would be to use the script element correctly: it should not have code inside its tags if there is a src attribute specified. Try:

```js
<script src='bignumber.js'></script>
<script>
let x = new BigNumber(144).toString();
document.write('<a>' + x + '</a>');
</script>
```

> By the way, I have heard that your library "only works at the block level". Is this true, and does it impact my problem? Are there restrictions about where your BigNumber objects can and cannot be invocated?

No, no, and no.

**Comment by PowerUser1234** [comment]
You've been absolutely right.  I now have things running just as desired.

-Is there a functions or trigonometry library I can use directly on your
BigNumber type in this library?

var pi = radian_arc_cosine(-1);
...

**Comment by MikeMcl** [comment]
Not that I am aware of, but see [decimal.js](https://github.com/MikeMcl).
