### ISSUE TITLE
Parser request

### ISSUE THREAD

**Issue by Light-Wizzard** [MikeMcl/bignumber.js#232]
I do not see a parser function, that would take an argument like: 
var thisValue = new BigNumber.parser("1 + 1 * 3 / 2");
and have the parser run the correct function for each math operation.

If you have one, can you point it out, if not can you add one as a request,
I am working on a Calculator this control, will link github repo when it works,
it would be real nice if you can paste in formula's in the calculator field, and have it parses it,
this way the Calculator is just building the string, and hitting = will parse it.

I have seen this in other Libraries, it makes life much easier.

For example:
https://mathjs.org/docs/expressions/parsing.html

I am working on something that will work for my needs, so far I have this:

```
function isInArray(thisItem, thisArray) {
    return thisArray.indexOf(thisItem.toLowerCase()) > -1;
}

function fixNumber(sThis) {
    let fThis = sThis + "";
    // if not a float return
    if (fThis.indexOf(".") < 1) return fThis;
    let newThis = "";
    let returnThis = "";
    let isPositive = 0;
    let i = 0;
    let signThis = "";
    if (fThis.charAt(0) === '-') signThis = "-";
    // reverse the numbers to rid 0 as last decimal
    for (i = fThis.length - 1; i > -1; i--) {
        //
        if (fThis.charAt(i) !== '-' && fThis.charAt(i) !== '+') {
            if (fThis.charAt(i) !== '0') {
                isPositive = 1;
            }
            if (isPositive === 1) {
                newThis = newThis + fThis.charAt(i);
            }
        } // end if
    } // end for
    // reverse the numbers
    for (i = newThis.length - 1; i > -1; i--) {
        returnThis = returnThis + newThis.charAt(i);
    } // end for
    if (returnThis.charAt(returnThis.length - 1) === ".") {
        returnThis = returnThis.substring(0, returnThis.length - 1);
    }
    return signThis + returnThis;
} // end fixNumber

function parse(thisEquation, sPrecision) {
    let fThis = thisEquation + "";
    fThis = fixNumber(fThis);
    if (fThis === "0.0") {
        console.debug("error parse(" + fThis + ", " + sPrecision + ")")
        return "0.0";
    }
    if (fThis === "0.0") {
        return "0.0";
    }

    let mathOperators = ["+", "-", "*", "/", "%", "(", ")"];
    let words = fThis.split(" ");
    let i = 0;
    let lastOperation = "";
    let theOperant = "";
    let theNumber = "";
    let theResult = "";
    let brackets = 0; // 0=No, 1=Start, 2=End
    for (i = 0; i < words.length; i++) {
        //console.debug("words[" + i + "]=|" + words[i] + "|");
        if (isInArray(words[i], mathOperators))  {
            //console.debug("isInArray math=|" + words[i] + "|");
            theOperant = words[i];
            lastOperation = "math";
            if (words[i] === "(") {
                brackets = 1;
            } else if (words[i] === ")") {
                brackets = 2;
            }
        } else {
            //console.debug("brackets=|" + brackets + "|");
            if (brackets === 0) {
                if (lastOperation === "math") {
                    //console.debug("lastOperation math=|" + theOperant + "|");
                    if (theOperant === "+") {
                        //console.debug("lastOperation=" + lastOperation + " theOperant=" + theOperant + " theNumber=" + theNumber + " ");
                        theResult = plus(theNumber, words[i], sPrecision);
                    } else if (theOperant === "-") {
                        theResult = minus(theNumber, words[i], sPrecision);
                    } else if (theOperant === "*") {
                        theResult = times(theNumber, words[i], sPrecision);
                    } else if (theOperant === "/") {
                        theResult = dividedBy(theNumber, words[i], sPrecision);
                    } else if (theOperant === "%") {
                        //theResult = plus(theNumber, words[i], sPrecision);
                    }
                } else {
                    // console.debug("number=|" + words[i] + "|");
                    theNumber = words[i];
                    lastOperation = "number";
                } // end if (lastOperation === "")
            } else if (brackets === 1) {

            } else if (brackets === 2) {

            } else {
                theNumber = words[i];
                lastOperation = "number";
            }
        }
    } // end for
    return theResult;
} // end parse

/* **********************************************************
 * test all functions
 */
function test() {
    console.debug("test Started");
    let storageVar = "";
    let thisTestString = "1234.6789";
    storageVar = fixNumber(thisTestString);
    if (storageVar !== thisTestString) {
        console.debug("test Failed: fixNumber(" + thisTestString + ") = |" + storageVar + "|")
    }
    thisTestString = "100000.000000";
    storageVar = fixNumber(thisTestString);
    if (storageVar === thisTestString) {
        console.debug("test Failed: fixNumber(" + thisTestString + ") = |" + storageVar + "| expected: 100000.0 or 100000")
    }
    // Test Math Parser
    storageVar = parse("1 + 1", 0);
    if (storageVar !== "2") {
        console.debug("test Failed: parse(1 + 1, 0) = |" + storageVar + "| expected: 2 or 2.0 depending on decimal places")
    }
    storageVar = parse("1 * 2", 0);
    if (storageVar !== "2") {
        console.debug("test Failed: parse(1 * 2, 0) = |" + storageVar + "| expected: 2 or 2.0 depending on decimal places")
    }
    storageVar = parse("4 / 2", 0);
    if (storageVar !== "2") {
        console.debug("test Failed: parse(4 / 2, 0) = |" + storageVar + "| expected: 2 or 2.0 depending on decimal places")
    }
    storageVar = parse("3 - 1", 0);
    if (storageVar !== "2") {
        console.debug("test Failed: parse(3 - 1, 0) = |" + storageVar + "| expected: 2 or 2.0 depending on decimal places")
    }

    console.debug("test Finished");
}

```

This is running in Qml, but should work in any JavaScript engine, and you can see the test pass, so the parser works, grant you it is over simplified, and needs some work, but it is a starting point, and I can finish my Calculator, without having to wait for this request.

The Galaxy Calculator and latest code for this example is at:

https://github.com/Light-Wizzard/galaxy-calculator

Thanks

**Comment by MikeMcl** [comment]
While I agree that it can be very useful, I don't want a parser to the library itself.

Math.js, which you link to in your post, uses my [decimal.js](https://github.com/MikeMcl/decimal.js) library under the hood and does an excellent job, so I would point people to that.

I wrote a parser several years ago for my [big.js](https://github.com/MikeMcl/big.js) library, but I didn't publish it. It was accessed using a `Big.eval()` method, for example:

```js
Big.eval('0.1 + 0.2');   // '0.3'
```

Here is the test file for it. It contains over 5000 tests. You may be able to edit it to test your own parser.
The parser could handle variables and function calls also, so those tests would need to be commented-out.  

[eval.zip](https://github.com/MikeMcl/bignumber.js/files/3058181/eval.zip)

**Comment by Light-Wizzard** [comment]
Thanks, I will look at it, do you think it will work better than what I stated to do, without using eval?

I know I can filter the input, making eval safe, but it is still eval, my question is does it use the same BigNumber functions to do the math?

This function is outside the Library, and works fine that way, so I see no reason to put it in the Library, it is better to keep it lean and mean, but it would be nice to create a standalone extra library, you only need to add the code to a wrapper, for example, I actually wrap all the functions in your library into a wraper I call BigMath.js, you can see it at the github repo.

https://github.com/Light-Wizzard/galaxy-calculator/blob/master/qml/BigMath.js

My concept of a Calculator, is that the interface only formats the command line, and when you hit =, it does the math, obviously I want it to use your library to do the math, how I do that is one of two ways, I either use an eval, or I have to parse it, eval is error prone, parser's can get confused with complex formulas, so you have to make a strict format policy, enforce spaces, and allowed characters for operators, and the brackets make programming fun, nested ones even more so, so I have to make a push and pull stack to keep track of Memory variables, so it is much slower, and how do I define multiple decimal places for different variables, I cannot do that in an eval, but could do it in a parser, making them slower, but more powerful as Equation Parser's, think about that, passing it in as json would allow you to define the precision and decimal place, and even what method to use to round, but the parser gets complex, the more functions it supports the more complex it becomes. In the past I have always used eval just to avoid a parser because of how complex they get, in the end I want it to handle everything I throw at it, so it is clear this should not be part of your library, since it is ongoing, meaning it will never be finished, always new equations it will need to be updated to run, and not everyone will need it, yet those that do, will want it, so it is a project in itself.

I do like the format for your eval, it allows you to find the variables, and makes algebra easy, so my thought is to have both methods, I can make an eval button, call it Algebra button, and switch to an Algebra editor screen.

I never could get Math.js to work, not sure why, a lot of Libraries did not work, I just tried it again, hoping it was the way I was importing it, but it wasn't, so I tried decimal.js, which lead me to BigNumber, which I got working, but due to import issue, I stepped on the namespace, not the case with other libraries I tied, but I did realize I could import as Math, and that will override everything in the Math library, which is what I wanted, since it was causing me so my grief, so I tried a lot of Libraries before I got any of them working right, in C++ I found a bug in boost, gmp worked, but did not have the tools to adjust decimal places, instead they use precision, meaning all digits, and not just the decimals, which is why your library works so well for my needs, so adding a function like modInverse to your Library, like this parser, they work well as a standalone, so maybe you can add them to demo's as standalone functions, adding more: as the need or code becomes available. You might think about adding some Qml demo's as well, I can cut out just the Calculator from my project and make it a standalone for you, currently it is a Felgo App, so I can also convert it to a normal Qml App to give you two demo's.

I am working on another project that uses a C++ back end, unless I can find another way to do this in JavaScript, but my goal is to write a Qt Qml App that will run a WebView in a Sandbox, so I can write this calculator in Qml, and this App will create a Website from it, this can be done using Qt, so I do not have to maintain two Apps, so when this is completed, I will have this Calculator for my website as well. If I write most of my code in JavaScript, it is not that hard to convert Qml controls into Web controls, there are even projects that do this, and even ones that can take HTML and convert it to Qml, and there are those that just do not like Qml, it can make cross platform Apps, and it can run WebView of any Website, what more can you ask for, but some people only care about the web and have no interest in Qml, but I am pretty sure the Qml programmer will like this concept, the idea is that it is code you upload to a specific folder in your current website, in form of a Qml file, it runs on the client side only, in a sandbox, so there is no reason to worry as much about virus and malware, you jail the folder they use for LocalStorage, and limit all access to the sandbox, yet offline you still have access to the data you created with the app, allowing you to make real time changes the code, and save it offline, in the sandbox, and allowing you to upgrade to newer versions of the app, so they only have to download it once, and only upgrade the files needed using something like rsync, so it is fast, making it possible to just open a file from github, and run it like an App in real-time, but my interest is mainly geared around your Library, so I have an interest in it, and making it better, not so much making it bigger, you have the right approach to this, and plugins or Function Libraries are much cleaner, I prefer Function Libraries in Qml, the two concepts are different, a plugin uses Protocols, a Function Library is what I created, it will create objects and work with them, but not extend them, nor integrate with them, meaning you have to update them if changes are made to newer libraries, making them separate projects, so that is my goal as well.

Thanks for the eval, let me know if it uses BigNumber to do all the math, my concept for a parser needs to be optimized, but I do plan on using both concepts, but if I can get eval to do everything I need, maybe the parser is too much work, because it is clear it is a lot of work just to get the basic functions to work, and I have not even started with the bracket parser yet, and function parser's are not that much fun, and the more complex the function gets, the more complex this parser gets, so it all comes down to how good the eval is, so I will work on that now, it could turn out to be all I needed, if they do use BigNumber, then it should work just as well at complex equations, only more accurate, which is the point..

**Comment by MikeMcl** [comment]
The `Big.eval` method I mentioned does not actually use JavaScript's built-in `eval` function, that's just the name I gave it. And yes, all the values it uses are *big.js* big numbers. 

The *eval.js* file I offered is just a large set of tests, and it does not include the implementation of the `Big.eval` method itself, but it should be easy to adapt so that you could thoroughly test your own parser.

**Comment by Light-Wizzard** [comment]
Do you have any examples of using this?

I found this in the code

`if ( !Big && typeof require === 'function' ) Big = require('../big-eval');`

Does this mean I need to have it installed via npm?

I need to make sure I take care of all my dependencies, since this is an application, it needs to ship with all its dependencies in order to run, and they must compile on Andriod and IoS, as well as Linux, Windows and MAC, and as usual, I have no idea how Qml JavaScript works with require, keep in mind that it is an old version of the standard, not the latest.

I did not see the actual eval function in the code, is it a prototype or is that what you mean it does not implement Big.eval, if so can you make that file available, so I can run the test in the script you gave me, and to use in my program, I did not see a repo for it, I am just getting back into JavaScript after years of only working with C++, and bash, and learning Qml at the same time, so it is not easy, but did not take much time to prototype my Calculator, now I need to make it fully functional.

What would be the best way to implement a full Big.eval, I guess I am a little confused about the code you gave me, it took me a while to figure out all the test code, at that point I thought this was just a test script for the actual Big.eval, which is what it sounds like from what you said, so I was wondering if you have another repo for it, or was this just a project you are still working on, or was working on, this has peaked my curiosity, because it sounds like it would simplify the code, I have to write a function for every math operation I support, grant you that might exceed that of an eval, but not without a lot of code, so far my parser does not even understand precedence,  the more I think about the code I need to write, the more I think I need to parse the whole equation into a tree, so I can set the precedence, otherwise I have to enforce brackets, and to confuse matters, I still use the old math precedence over the new when using Newtons equations, but this requires spaces between all math operators, or loading them as json, which is not a bad idea, my original concept was set rules based on brackets to set the precedence, this is a very old method, Newton used it, as did others of his time, over the ages it became a standard to use precedence over brackets, personally I always found it easier to define precedence with brackets then to remember all the rules, I guess I never should have learned languages like the Air Force made us, it was all very bracket intense, and all 3 types mean something different, you have [], () and {}, Lions, Tigers and Bears, Lions are Arrays, Tigers are expression delimiters, and Bears are definitions defined in the Array, that is actually how they taught us how to remember which one was used for what, the roots of LISP data types is what it turned out to be, this format was used as part of CIIL, Common Intermediate Interface Language, not to be confused with CIL, this was used mainly by Westinghouse and Techtronics, my point is that it was well-thought-out standard for doing what I need, and I can not even find it on the internet, but that was before it was invented, at any rate, it is just an idea, I could do the same thing with just (), and simplify it, but that would also make it less powerful, but it was designed to be used to pass math equations between different devices, like a Millimeter and an O-Scope, so it has a well-defined standard, in use, the [] meant everything inside it had to be completed before moving on, and could be used to separate multiple request [()()] + [()( ())], I leave out the numbers to make it easier to see, and these could be nested, for example you can define an Equation as a tag string, and you can nest them [(){}], parsing it, when you hit [ you have to run everything inside it till you ht the ], to end it, and it always runs left to right with no precedence for math operand, such that you use () to group expressions that run left to right, and you use {} as a function of x, and it can be used to drive very complex equations, without the need for precedence, but it is a very old standard not really in use today, they say old people start remembering the old days like they still existed, but json has its own way of defining what these brackets means and how to use them, and in the end, it all depends on the method I used to run the equation, on one hand I thought about just using your notation, and just running a JavaScript eval, this runs on the client side, but still, this is not really all that safe to do, who knows why a person would cut and paste in an express they know will run on their system, without knowing what it is doing, you know, the Evil Eval, and really that is what keeps me thinking about a parser, but I realize my first attempt needs a road map, all I am really doing is building function calls to return the correct results, this way I am guaranteed the math is done using the right function, but it runs left to right, so it all comes down to precedence, so I need to set how I can map that out before I get to far into this function, I always jump in and try to figure it out as I go, not always the best way to get the results you need. 

No mater what rules I set forth when making a calculator that accepts manual input, it can never really account for every ones needs,  and using an outdated parsing format as the one I used for embed devices, that had to parse on the fly, I found it to be very efficient at what it did, but still, it is not a standard language for Math Equations, I like the concept you have of using json to pass in the variables, it would not be that hard to write an equation editor that was programmable, but this two is a non-standard way of doing things, but then again, its standard once you start doing it that way, so really no reason to stick with a standard, but what every you go with, it has to work. 

This is a lot to think about, I have looked at a lot of equations in my lifetime, and always run into the same problem, precedence, sure I can just pop them into a tree structure, so I can execute the nodes in the correct order, or I can use eval... I really want to do what works the best, but I do not know what that is.

**Comment by MikeMcl** [comment]
> Do you have any examples of using this?

The test file can be run in either a browser or Node.js. 

In a HTML document for a browser:
```html
<script src='path/to/eval.js'></script>
```
Node.js:
```bash
$ node eval
```
> I found this in the code  `if ( !Big && typeof require === 'function' ) Big = require('../big-eval');` Does this mean I need to have it installed via npm?

That line should be removed. It is just making sure `Big` is available. Your parser won't be using *big.js* so there won't be a `Big` function. 

> I have no idea how Qml JavaScript works with require.

If your parser uses `BigNumber`, then you would load it uses `import` as discussed in your previous issue. But anyway, here, we are just talking about testing your parser, which you could do with Node.js or a browser as shown above.

> I did not see the actual eval function in the code, is it a prototype or is that what you mean it does not implement Big.eval, if so can you make that file available, so I can run the test in the script you gave me, and to use in my program, I did not see a repo for it,

I am not sure I want to make that available at present. You can adapt the test file to your own parser. Mainly, it is just a matter of changing the `T` function from

```js
function T( dp, rm, expression, expected, scope ){
    Big.DP = dp;
    Big.RM = rm;
    // Use toFixed to avoid exponential notation.
    assert( expected, Big.eval( expression, scope ).toFixed() );
}
```
to, something like the following, which assumes you are using `BigNumber` and that your parser function is `parse`:
```js
function T(dp, rm, expression, expected){
    BigNumber.config({ DECIMAL_PLACES: dp, ROUNDING_MODE: rm });
    assert(expected, parse(expression));
}
```
> I am just getting back into JavaScript after years of only working with C++, and bash, and learning Qml at the same time, so it is not easy

Yes, I can understand that. Re-learning JavaScript at the same time as Qml woiuld be confusing.

Regarding handling precedence by inserting brackets, yes, you could do, but that is perhaps a less efficient way of doing it. I based my `Big.eval` method on the article [Top Down Operator Precedence](http://javascript.crockford.com/tdop/tdop.html) by Douglas Crockford, although I am not claiming that is the best way of doing it. I am sure there are a lot of very good parsers already available on Github, so you might not want to re-invent the wheel here. I don't recommend using JavaScript's built-in `eval` function.

**Comment by Light-Wizzard** [comment]
I found this one: 

https://github.com/silentmatt/expr-eval

I am sure there are more out there, but do you think this could be modified to work with your Library?

I have this issue with Math.js
https://github.com/josdejong/mathjs/issues/1454

I was wonder if you think this could be modified to work:

https://github.com/josdejong/mathjs/blob/develop/src/expression/Parser.js

I take it your Big-Parser is not finished, from the work you did on it, I take it you were interested in this at one time also, just wondering what the status was on your work?

I agree about not reinventing this code, and my effort was too simplistic, I liked the article you linked to above, and see how that works, I imagine I can edit it to make it work, it is just a matter of finding out what the easiest way of doing this without reinventing the wheel.

Thanks

**Comment by MikeMcl** [comment]
See [#1454](https://github.com/josdejong/mathjs/issues/1454)

**Comment by MikeMcl** [comment]
I have adapted the `big.eval` method I mentioned above for *bignumber.js* and tested it with QML, and it works fine.

```qml
import QtQuick 2.9
import QtQuick.Window 2.2

import "bignumber.js" as Bignumberjs

// Add the 'evaluate' method to the global 'BigNumber' object.
import "evaluate.js" as Evaluatejs

// Uncomment to run the test file (takes 40 seconds and prints to the console).
//import "test.js" as Testjs

Window {
    visible: true
    width: 800
    height: 200

    Text {
        id: myText
        font.pointSize: 25
        anchors.centerIn: parent
    }

    function startup() {
        const result1 = BigNumber.evaluate('0.1 + 0.2');
        const scope = { x: '1.000000000000000000000001', y: 3, z: 4.5 };
        const result2 = BigNumber.evaluate('2y(4x + 1) - z', scope);
        myText.text = result1.toString() + '\n' + result2.toString();
    }

    Component.onCompleted: startup();
}
```

[Evaluate.zip](https://github.com/MikeMcl/bignumber.js/files/3073181/Evaluate.zip)

This gives you an alternative to *math.js* if that is a bit heavyweight.
