### ISSUE TITLE
How to remove trailing zeros?

### ISSUE THREAD

**Issue by mqklin** [MikeMcl/bignumber.js#235]
Is there any way to remove trailing zeros after `toFixed` call? For example: 
```
function div(x, y) {
  return BigNumber(x).div(y).toFixed(5);
}
div(1, 2); // -> 0.5, not 0.50000
div(1, 3); // -> 0.33333
```

**Comment by MikeMcl** [comment]
See [decimalPlaces](http://mikemcl.github.io/bignumber.js/#dp).

```js
function div(x, y) {
  return BigNumber(x).div(y).decimalPlaces(5).toString();
}
div(1, 2); //   0.5
div(1, 3); //  0.33333
```

**Comment by mqklin** [comment]
Thank you!

**Comment by ReZeroS** [comment]
It seems this way has a precision limitation, when I try `BigDecimal(0.0000000001).decimalPlaces(10).toString`, it would return 1e-9. (scientific notation not the 0.0000000001)

**Comment by AoDev** [comment]
@mqklin 

Is it possible to remove trailing zeros with `toFormat()`? 
I need to be able to format separators and I don't want trailing zeros.

**Comment by mqklin** [comment]
Not sure, better ask @MikeMcl

**Comment by AoDev** [comment]
Sorry @mqklin , I meant to ping @MikeMcl instead.

**Comment by MikeMcl** [comment]
> Is it possible to remove trailing zeros with toFormat()?

No, it isn't.
