### ISSUE TITLE
v9 published but only v8.1 docs?

### ISSUE THREAD

**Issue by bradennapier** [MikeMcl/bignumber.js#237]
just noticed that v9 is the latest npm but only the docs for v8.1 are published.  is there no difference?  what is in the major release that is considered breaking?  is there migration steps?

---

**edit** - i see that it just seems to remove symbol for compatibility reasons?

**Comment by MikeMcl** [comment]
Yes, I received reports by email that the `Symbol` code was breaking the library in IE8, so I removed it. There is no difference in the docs. There are no migration steps. If you have a suggestion or criticism in that regard, please elaborate.

Github seems to be struggling to produce the diff, but basically I just took out the following:

```js
  P[Symbol.toStringTag] = 'BigNumber';
  P[Symbol.for('nodejs.util.inspect.custom')] = P.valueOf;
```

Strictly-speaking this was a breaking change so annoyingly I had to increment the major version number.

**Comment by bradennapier** [comment]
Thanks, appreciate it!

**Comment by mqklin** [comment]
@MikeMcl it would be good if you put some info in the release notes: https://github.com/MikeMcl/bignumber.js/releases/tag/v9.0.0
I've just wanted to create the same issue to understand what are the changes in 9.0.0.
Thanks!

**Comment by MikeMcl** [comment]
@mqklin 

I have added a brief note.

Thanks for your input.

**Comment by mqklin** [comment]
Cool, thanks a lot!
