### ISSUE TITLE
Type error on Indexer Property

### ISSUE THREAD

**Issue by SebastienGllmt** [MikeMcl/bignumber.js#238]
On Feb 20th, [this commit](https://github.com/MikeMcl/bignumber.js/commit/788335bc99c1c42b567655edad5be507b2e0a993#diff-4fc5bc03c83b2baae6f575a047295455) REMOVES the indexer property on `BigNumber`

On Feb 24th, [this commit](https://github.com/MikeMcl/bignumber.js/commit/165c9bccab58f7c98d0e57de1d624eb5154e25f7#diff-4fc5bc03c83b2baae6f575a047295455) ADDS the indexer property to `Instance` (which `BigNumber` implements)

Because of this we now have a type error: `Instance` has an indexer property, but BigNumber (which inherits from `Instance`) doesn't.

**Comment by reslake** [comment]
Wallet Transfer
ether token account

**Comment by MikeMcl** [comment]
Thanks for the report, such as it is.

See #208 for background.
