### ISSUE TITLE
About DEC64

### ISSUE THREAD

**Issue by SamLebarbare** [MikeMcl/bignumber.js#240]
http://dec64.com/
https://github.com/douglascrockford/DEC64

**Comment by MikeMcl** [comment]
Yes, I have visited those links before - they're great.
But what exactly is the issue here?

**Comment by SamLebarbare** [comment]
By curiosity, can you explain me, if we have the same range of values capabilities with BigNumber, and if we can gain performances by wrapping an ASM.js impl. behind the scene.

No doubt, that bignumber is suitable and already performant for all case of computing.

You can close this "curio'issue" ;)

**Comment by MikeMcl** [comment]
Your question is not clear to me, but DEC64 seems to be limited to 17 significant digits and exponents in the range -127 to 127, so it does not have the same capabilities as this library. I am sure that using asm.js could result in performance gains, yes.
