### ISSUE TITLE
¿How to implement trig functions and its inverses using BigNumber.js?

### ISSUE THREAD

**Issue by PedroUrday** [MikeMcl/bignumber.js#243]
I need them because a formula makes use of trig functions.
With the sine and cosine functions I can implement the rest of the trig functions. But, what about the inverse functions?

**Comment by MikeMcl** [comment]
See [decimal.js](https://github.com/MikeMcl/decimal.js).

**Comment by ronknott** [comment]
Mike
I have a library of the trig functions and inverses, hyperbolic trig and inverses, logs and exp and others (Gcd,Lcm etc) all for BigNumbers. It needs a Help file which I am preparing. I will try to upload it probably on Sunday 11th but let you know here. 
Ron Knott

**Comment by ronknott** [comment]
I have now uploaded BigNumberLIB.js with a help file at
http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/BigNumberLIB/index.html <http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/BigNumberLIB/index.html>
 It covers some integer functions (gcd, lcm, powmod) trig functions and inverses and hyperbolic functions and inverses and a link to a page where I use all of these and where you can try them out.

Comments etc welcome to ronknott@mac.com <mailto:ronknott@mac.com>

**Comment by MikeMcl** [comment]
Great work, Ron. I will put a link to your page on the README here.
