### ISSUE TITLE
Can't import ES6 Module

### ISSUE THREAD

**Issue by cliffhall** [MikeMcl/bignumber.js#244]
Seeing this when trying to use bignumber.js in React.

```
npm install bignumber.js --save
...
+ bignumber.js@9.0.0
added 1 package and updated 1 package in 42.022s
```

In MyEntity.js:
```
import BigNumber from "./bignumber.mjs";
```

Webstorm hint:
```
Cannot resolve file 'bignumber.mjs' 
```
Running MyEntityTest.js with jest:
```
Cannot find module './bignumber.mjs' from 'MyEntity.js'
```

**Comment by MikeMcl** [comment]
This is nothing to do with *bignumber.js*.

If you are using

```js
import BigNumber from "./bignumber.mjs";
```

then obviously the *bignumber.mjs* file would have to be in the same directory as *MyEntity.js*. 

Let me guess - it isn't.

If you are trying to import the library from a *node_modules* directory, then just use 

```js
import BigNumber from "bignumber.js";
```

as the name of the library is "bignumber.js".

BTW Your comment in the linked issue was ignorant and offensive:

> BigNumber.js (which even in 9.0.0, I'm still unable to use the ES6 module import with).

**Comment by cliffhall** [comment]
@MikeMcl I tried all valid paths, not just “./“ I left it there because, literally from the README of this project:
![B649076B-D16F-45F4-861B-09D3A8722EB1](https://user-images.githubusercontent.com/871933/63189667-78da9700-c032-11e9-90e4-e750b2c8ebd5.png)

No biggie. I moved on to JSBI, which offers a BigInt implementation based on the spec that will sone be incorporated into the language and that nearly matches the performance of the currently shipping Chrome browser implementation.

**Comment by MikeMcl** [comment]
Yes, the README shows a perfectly good example of how to load the library as an ES module.

It assumes that the reader knows the basics of how ES modules work.

**Comment by cliffhall** [comment]
Dude, dial back the hostility. I do know how modules work. Your readme however shows npm install to node_modules followed by an import from ./ which is not going to work. I tried the proper path and variations to reach the mjs file. The import in the above was contrived, pasted from your readme. Sorry I quoted the advice that assumes you have the file in the local folder with your code which nowhere in your readme do you show happening. That part was an honest mistake as I’m sure is the case on your readme.
