### ISSUE TITLE
Precision not maintained on division

### ISSUE THREAD

**Issue by josdejong** [MikeMcl/bignumber.js#25]
I noticed some unexpected behavior when dividing numbers. In the following example I have set the precision to 10 decimal places. I expected this to be the number of significant digits, but apparently this means the number of significant digits _behind the decimal point_.

In the following example I would expect each of the results to be in the format `1.666666667e[+-]EXP`: each time having 10 digits, and the value of `EXP` being equal to the exponent of the divided value. Instead, the number of digits varies depending on the values exponent.

``` js
BigNumber.config(10);

console.log(new BigNumber('5e-15').div('3').toExponential()); // "0e+0"
console.log(new BigNumber('5e-10').div('3').toExponential()); // "2e-10"
console.log(new BigNumber('5e-5').div('3').toExponential());  // "1.66667e-5"
console.log(new BigNumber('5e+0').div('3').toExponential());  // "1.6666666667e+0"
console.log(new BigNumber('5e+5').div('3').toExponential());  // "1.666666666666667e+5"
console.log(new BigNumber('5e+10').div('3').toExponential()); // "1.66666666666666666667e+10"
```

Is this intended behavior? If so, is there any workaround so I can actually do divisions on small values without loosing precision?

**Comment by ruimarinho** [comment]
@MikeMcl does this explain why `new BigNumber('1.1').dividedBy('2').times(new BigNumber(2).dividedBy('1.1')).toString()` returns `1.000000000000000000001` and not `1`?

**Comment by MikeMcl** [comment]
`2 / 1.1` has a non-terminating decimal expansion (an infinite number of digits after the decimal point), which means that the result of `BigNumber(2).dividedBy(1.1)` will only be an approximation.

    BigNumber.config().DECIMAL_PLACES   // 20
    BigNumber.config().ROUNDING_MODE    // 4
    new BigNumber(2).dividedBy(1.1)     // 1.81818181818181818182

BigNumbers are stored as floating-point values not ratios.

**Comment by ruimarinho** [comment]
Ok, so because BigNumbers are stored as floating-point and not ratios, then the lib is unable to cancel the ratios and return exactly `1`, correct? In that case, should the number of `DECIMAL_PLACES` be increased in order to cover the necessary precision? Is this what decimal.js does?

**Comment by MikeMcl** [comment]
Infinite precision would be needed in order to return exactly `1`.

decimal.js works using significant digits instead of decimal places, but it also stores numbers in a floating-point format so it wouldn't make any difference here. 

Your choices would seem to be to either find a library that stores numbers as ratios or just round the result.

    a = new BigNumber(1.1).dividedBy(2)
    b = new BigNumber(2).dividedBy(1.1)
    a.times(b).round()      // 1
    a.times(b).round(10)    // 1
    a.times(b).round(19)    // 1
    a.times(b).round(20)    // 1
    a.times(b).round(21)    // 1.000000000000000000001
