### ISSUE TITLE
Cannot create bignumber instance without `new`

### ISSUE THREAD

**Issue by jurosh** [MikeMcl/bignumber.js#251]
There is problem creating instance of bignumber in typescript (probably also in JavaScript)

```
import BigNumber from 'bignumber.js';
const bn = BigNumber('0.123');
```

There is error : `Value of type 'typeof BigNumber' is not callable. Did you mean to include 'new'?`

As per doc `new` keyword for creating instance of Bignumber should not be required.

**Comment by djmattyg007** [comment]
Is there an issue with using `new`? It is meant to be used as a class after all.

**Comment by MikeMcl** [comment]
> There is problem creating instance of bignumber in typescript (probably also in JavaScript)

No, it's just in typescript.

[This](https://stackoverflow.com/questions/32807163/call-constructor-on-typescript-class-without-new) stackoverflow post seems to give some workarounds but I am not going to try and fix this issue myself.  

I recommend that typescript users just use `new`.

Of course, if someone wants to amend the *bignumber.d.ts* file to fix this issue then a PR wpuld be welcome.
