### ISSUE TITLE
missing doc for BigNumber.sum()

### ISSUE THREAD

**Issue by MathieuDerelle** [MikeMcl/bignumber.js#257]
I spent some time trying
`BigNumber.sum([x,y,z])`

I had to check the [unit tests](https://github.com/MikeMcl/bignumber.js/blob/master/test/methods/sum.js) to figure out, you need to pass them as arguments
`BigNumber.sum(...[x,y,z])`

**Comment by MikeMcl** [comment]
Or you can use [apply](https://mikemcl.github.io/bignumber.js/#sum).
