### ISSUE TITLE
Is there any method could get the last meaning digit ratio as step?

### ISSUE THREAD

**Issue by ReZeroS** [MikeMcl/bignumber.js#261]
😥 Well, I don't know what‘s the correct definition for "the last meaning digit ratio", it just for example:

```
123 => 1
123.021 => 0.001
133.4500 => 0.01 
2.0 => 1
```

**Comment by MikeMcl** [comment]
There is no built-in method to do this, but it shouldn't be too difficult using the `dp` or `decimalPlaces` method:

For example

```js
BigNumber.prototype.step = function () {
  return 10**-this.dp();
};

let x = new BigNumber('133.4500');
x.step();    // 0.001

x = new BigNumber('123');
x.step();    // 1
```
