### ISSUE TITLE
reuse bignumber object

### ISSUE THREAD

**Issue by shangdibaozi** [MikeMcl/bignumber.js#264]
```a.multipliedBy(b)``` always return a new bignumber object。

Expect to support this writing
```
let tmp = new BigNumber();
let a = new BigNumber(11);
BigNumber.multipliedBy(a, 2)

a.toString(); // 22
```

**Comment by MikeMcl** [comment]
You can write:

```js
a = new BigNumber(11);
a = a.multipliedBy(2);
a.toString();    // '22'
```

**Comment by shangdibaozi** [comment]
> You can write:
> 
> ```js
> a = new BigNumber(11);
> a = a.multipliedBy(2);
> a.toString();    // '22'
> ```

**Comment by shangdibaozi** [comment]
In my game, i'll do many operation each frame, it'll create many new BigNumber object.
```
a = new BigNumber(11);
a = a.multipliedBy(2);
a.toString();    // '22'
```

**Comment by MikeMcl** [comment]
In-place operations could be supported using, for example:

```js
inPlace = true;
a = new BigNumber(11);
a.multipliedBy(2, inPlace);
a.toString();    // '22'
```

Unfortunately, I have little to no interest in doing the considerable work that this would involve, particularly as I expect that any performance gains would be insignificantly small or non-existent for the vast majority of use-cases.
