### ISSUE TITLE
Any way to add a warning when comparing with "==="?

### ISSUE THREAD

**Issue by PachowStudios** [MikeMcl/bignumber.js#265]
It's very easy to accidentally try to compare two BigNumbers with `===` instead of `.isEqualTo()`.

Is there any way to throw an error or show a warning when doing this? I understand it might not be possible within the library, but maybe a custom ESLint rule?

**Comment by MikeMcl** [comment]
> Is there any way to throw an error or show a warning when doing this?

I don't think so.

> maybe a custom ESLint rule?

Sorry, but I can't help with that.
