### ISSUE TITLE
Fractional power

### ISSUE THREAD

**Issue by rsbondi** [MikeMcl/bignumber.js#27]
console.log(Math.pow(9,0.5)); // outputs 3 as expected
  console.log(new BigNumber(9).pow(0.5)); // Uncaught BigNumber Error: pow() exponent not an integer: 0.5

**Comment by or2008** [comment]
was it implemented? 

is there a way to use fractional power (not just 0.5) with this library?

**Comment by MikeMcl** [comment]
No, when I added fractional powers it was so much added code that I decided to make further changes and release it as a new library [decimal.js](https://github.com/MikeMcl/decimal.js).
