### ISSUE TITLE
Is it possible to limit the decimals on scientific notation with toString?

### ISSUE THREAD

**Issue by rafael-lua** [MikeMcl/bignumber.js#273]
Hello. I want to do the following:

In the readme example, the toString() method returned "1.111222233334444555566e+21". Is it possible to limit the amount of decimals so the value shown would be "1.1112e+21" instead?

**Comment by MikeMcl** [comment]
```javascript
let x = new BigNumber('1111222233334444555566');
console.log(x.toExponential(4));           // '1.1112e+21'
console.log(x.precision(5).toString());    // '1.1112e+21'
```

**Comment by rafael-lua** [comment]
@MikeMcl 

Oh, thank you! And sorry for the obvious question.
