### ISSUE TITLE
Built-in S-expression calculator

### ISSUE THREAD

**Issue by septs** [MikeMcl/bignumber.js#280]
```ts
// 1 + 2
BigNumber.calc('+', '1', '2')
// 1 + (2 * 3)
BigNumber.calc('+', '1', ['*', '2', '3'])
// 10 * (10 ** 100)
BigNumber.calc('*', '10', ['**', '10', '100'])
// 5 - (6 * 7)
BigNumber.calc('*', '-', '5', '6', '7')
// etc
```

by built-in polish notation calculator simplify code and logic.

see https://en.wikipedia.org/wiki/Polish_notation
see https://en.wikipedia.org/wiki/S-expression

**Comment by MikeMcl** [comment]
Are you suggesting that I implement this?

I have extended my other library *decimal.js* with an [expression evaluator](https://github.com/MikeMcl/decimal.js-extensions/tree/master/evaluate).
