### ISSUE TITLE
In react project, report a compile error

### ISSUE THREAD

**Issue by Sirormy** [MikeMcl/bignumber.js#287]
./node_modules/bignumber.js/bignumber.js
  Line 2008:17:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

```js
if (xLTy) t = xc, xc = yc, yc = t, y.s = -y.s;
```

hot to fix it?

**Comment by shuckster** [comment]
Looks like you have an `eslint` rule that's looking at your `node_modules` folder.

Make an `.eslintignore` file and put `node_modules` in it.
