### ISSUE TITLE
Uncaught (in promise) Error: invalid BigNumber value

### ISSUE THREAD

**Issue by kukudedaxia** [MikeMcl/bignumber.js#290]
![image](https://user-images.githubusercontent.com/30620856/115988710-86109d00-a5ed-11eb-9395-793085699202.png)

https://stackoverflow.com/questions/66193724/bignumber-js9-0-1-which-was-used-for-dapp-over-aws-s3-causes-an-invalid-big

**Comment by kukudedaxia** [comment]
My local is normal, but the production environment is not working

**Comment by MikeMcl** [comment]
I don't think you are using this library. There is no *bignumber.ts* file here or any error message which states "invalid BigNumber value". 

From your link:

> I assumed that it might happen if the bignumber.js version is deprecated to 5.0.14.

There isn't a bignumber.js version 5.0.14. Again, I don't think this library is being used.

**Comment by kukudedaxia** [comment]
I was normal in the test environment, but an error was reported in the production environment. I think it may be that babel did not use commonJS to transfer bignumber.

**Comment by jjhesk** [comment]
> I don't think you are using this library. There is no _bignumber.ts_ file here or any error message which states "invalid BigNumber value".
> 
> From your link:
> 
> > I assumed that it might happen if the bignumber.js version is deprecated to 5.0.14.
> 
> There isn't a bignumber.js version 5.0.14. Again, I don't think this library is being used.

This error message is occurred from the web3.js.

**Comment by MikeMcl** [comment]
> This error message is occurred from the web3.js. 

And? What is your point? 

Why have you created an issue here? [web3.js](https://github.com/ChainSafe/web3.js) doesn't even use this library.

Stop spamming closed issues.
