### ISSUE TITLE
Last digit of number is round off when number of digits length is 20

### ISSUE THREAD

**Issue by Soni-Goyal** [MikeMcl/bignumber.js#292]
My data is coming from third party API in node and this data contains an id of number type whose number of digits are 20(69673776659654677224). They don't provide any string format.

After trying this library, my last digit is still truncated
when i try to do new BigNumber(id).toFixed()
Hence doesn't provide correct id to me

Can someone please help how to handle it ?

**Comment by MikeMcl** [comment]
It's not an issue with this library. 

```js
Number(69673776659654677224)    // 69673776659654680000
```

Basically, you need to put quotes around the values before you parse them.

See, for example, [parse json with large numbers](https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigint) or [convert an extra large number to string in json](https://stackoverflow.com/questions/53022343/javascript-convert-an-extra-large-number-to-string-in-json-before-the-default) etc.

**Comment by Soni-Goyal** [comment]
Thanks its working using JSON.stringify replace method
