### ISSUE TITLE
LICENCE.MD should be LICENSE.MD

### ISSUE THREAD

**Issue by acicali** [MikeMcl/bignumber.js#293]
BigNumber rocks!

**Comment by MikeMcl** [comment]
Why do you think that? In British English the noun is licence, not license.

**Comment by acicali** [comment]
DOH! Sorry for looking at it through my American-centric lenses. Github's project page template uses 'License' on the right ->

I should've known given the attention to detail of BigNumber's documentation that this was spelled correctly. <spankings>

Thank you for BigNumber.
