### ISSUE TITLE
multipliedBy work incorrect

### ISSUE THREAD

**Issue by pripersian** [MikeMcl/bignumber.js#299]
We have code
```
var MulNumber = BigNumber(4563579969884408065).multipliedBy(997).toFixed();
console.log(MulNumber);
```
We have result 4549889229974755075100

But in calculator or other library we have result = 
![image](https://user-images.githubusercontent.com/68734432/127132446-a74152b6-ee2c-41e2-874d-a0b66d363191.png)
4549889229974754840805

**Comment by Brucedayton** [comment]
why you use toFixed()?

**Comment by MikeMcl** [comment]
@Brucedayton

`toFIxed()` is used to ensure that exponential notation is not used.

Conversely, `toExponential()` is used to ensure that exponential notation is used.

The mistake made above is that  `4563579969884408065` should have been passed as a string, as it is too large for a JavaScript number.
