### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by unfernandito** [MikeMcl/bignumber.js#307]
Hello @MikeMcl 

The lib is actively maintained or do you need help with it?

**Comment by MikeMcl** [comment]
Hello

Yes, absolutely it is maintained. Any important issues that are raised are attended to straight away.

I'm not looking to expand the API here, but if there are any particular issues or ideas you want to work on then I am open to that.

Thanks for your offer.

**Comment by unfernandito** [comment]
Hello

Thanks You Mike. 

If i see something where i can help, i'll be make a PR to this repo.

Regards
