### ISSUE TITLE
Mixed-case numbers not parsed

### ISSUE THREAD

**Issue by jbrower2** [MikeMcl/bignumber.js#309]
If a string input has mixed-case letters, the value will fail to parse. If this is expected, it should be clarified in the documentation. I dug in to the code and it appears that it's doing a pseudo-case-insensitive match, but will only work if the input is entirely uppercase or lowercase.

Input:
```typescript
console.log(new BigNumber("0xab"));
console.log(new BigNumber("0xAB"));
console.log(new BigNumber("0xaB"));
```

Output:
```
171
171
NaN
```

Fixing this may prove difficult, considering case-sensitive alphabets exist and should remain supported.

It may be overkill, but I would recommend a solution where alphabets are stored as an object rather than a string, that way we can do analysis of the alphabet when it is constructed and determine metadata like case-sensitivity, etc.

> (Side note; not really part of this issue) This above solution may help solve #250. I'm imagining there would exist some `DEFAULT_ALPHABET` constant. The concern with the solution mentioned in #250 is that the check `ALPHABET.slice(0, 10) === '0123456789'` would be somewhat slow to add in to a hot path. But if we are able to do something like `ALPHABET === DEFAULT_ALPHABET`, a reference equality check should be very fast and mitigate this concern.

**Comment by MikeMcl** [comment]
The behaviour is intended, and personally I am not inclined to lift a finger to make that explicit in the docs. 

`ALPHABET === DEFAULT_ALPHABET` could only be true if `DEFAULT_ALPHABET` was exposed to the user (and therefore vulnerable to unwanted change).

I am also not inclined myself to do any more work on the user-defined alphabet functionality. It's a bit niche and left-field anyway, and I don't think the vast majority of users ever use it. I think just adding a note to the docs will suffice for #250. 

Of course, I would be happy to give feedback on and potentially accept other ideas/PR's on the matter.

**Comment by jbrower2** [comment]
I think it's hard to say this behavior is intended when it's undocumented and is not in line with how most languages parse hexadecimal literals.

> Surely, ALPHABET === DEFAULT_ALPHABET could only be true if DEFAULT_ALPHABET was exposed to the user (and therefore vulnerable to unwanted change).

I think I may have misconstrued what I was intending with this. I was thinking `DEFAULT_ALPHABET` would be internal to the library, and that `ALPHABET === DEFAULT_ALPHABET` check would be where the 'base 10' special case already exists ([link](https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.js#L255)).

I believe a solution would be fairly trivial to implement. I will give it a try and report back.

**Comment by MikeMcl** [comment]
> I think it's hard to say this behavior is intended when it's undocumented and is not in line with how most languages parse hexadecimal literals.

For user-defined 'alphabets' that include lower and upper-case versions of letters, the numerical value of a letter necessarily differs depending on its case, so it seems inappropiate to ever allow mixed case letters in the same string to have the same numerical value. The use of mixed case values for single-case-alphabet bases is more likely to be a mistake on the users part, and it is for me the better choice to disallow it.

**Comment by MikeMcl** [comment]
> I think it's hard to say this behavior is intended when it's undocumented and is not in line with how most languages parse hexadecimal literals.

Other languages do not allow user-defined 'alphabets' that include lower and upper-case versions of letters. In such alphabets, the numerical value of a letter necessarily differs depending on its case, so it seems inappropiate to ever allow mixed-case letters in the same string to have the same numerical value. The use of mixed case values for single-case-alphabet bases is more likely to be a mistake on the users part.

**Comment by MikeMcl** [comment]
See #310
