### ISSUE TITLE
shiftedBy unexpected output

### ISSUE THREAD

**Issue by blake256** [MikeMcl/bignumber.js#312]
Hello @MikeMcl 

I'm not sure if this is intended behavior or not but the following conversion returns an unexpected value:

`new BigNumber(1.111111111111111111).shiftedBy(18).toFixed()`

`1111111111111111200` = actual
`1111111111111111111` = expected

1. Maybe I'm missing some rounding configuration option or something else?
2. `shiftedBy(18)` is the same as `times(new BigNumber(10).pow(18))` correct?

**Comment by shuckster** [comment]
One of the reasons APIs like `BigNumber` exist is to avoid the problems of the native JavaScript number type, which you've provided as input.

To fix it, use a string instead:

```js
new BigNumber('1.111111111111111111').shiftedBy(18).toFixed()
// "1111111111111111111"
```

**Comment by blake256** [comment]
> One of the reasons APIs like `BigNumber` exist is to avoid the problems of the native JavaScript number type, which you've provided as input.
> 
> To fix it, use a string instead:
> 
> ```js
> new BigNumber('1.111111111111111111').shiftedBy(18).toFixed()
> // "1111111111111111111"
> ```

Good point, thank you very much ser!
