### ISSUE TITLE
Wrong return type of decimalPlaces()

### ISSUE THREAD

**Issue by pobch** [MikeMcl/bignumber.js#319]
According to the doc:

> If dp is omitted, or is null or undefined, the return value is the number of decimal places of the value of this BigNumber, **or null if the value of this BigNumber is ±Infinity or NaN**

By the way, the return type of `decimalPlaces()` is just `number`, which is wrong. The correct type should be `number | null`.

**Comment by MikeMcl** [comment]
Thank you for letting me know.

**Comment by lukelu0520** [comment]
Got the same issue +1 Was wondering which version can resolve the issue. Thx.

**Comment by MikeMcl** [comment]
@lukelu0520 

I'm sure you can find that out for yourself.
