### ISSUE TITLE
The number is wrong

### ISSUE THREAD

**Issue by A1103229475** [MikeMcl/bignumber.js#325]
` let a = new BigNumber(273862376557801659)`
`console.log(a.toNumber())    // 273862376557801660`

**Comment by shuckster** [comment]
You need to pass strings to BigNumber:

    BigNumber('273862376557801659')

Libraries like this exist to get around problems with the native number-type, which is the cause of your problem, so try to avoid using it and work with strings as much as possible.

**Comment by MikeMcl** [comment]
There is no JavaScript number with value `273862376557801659`.

```js
console.log(273862376557801659);    // '273862376557801660'
```
