### ISSUE TITLE
higher accuracy

### ISSUE THREAD

**Issue by windkind88** [MikeMcl/bignumber.js#328]
How do you display higher accuracy？
example
```
x = new BigNumber('2');
z=x.sqrt()
console.log(z.toFixed());
```
now :     1.4142135623730950488
i hope:   1.414213562373095048801688724...

**Comment by shuckster** [comment]
[BigNumber.config({ DECIMAL_PLACES: * })](https://mikemcl.github.io/bignumber.js/#decimal-places)

**Comment by windkind88** [comment]
> [BigNumber.config({ DECIMAL_PLACES: * })](https://mikemcl.github.io/bignumber.js/#decimal-places)

thx！

**Comment by MikeMcl** [comment]
`BigNumber.config({ DECIMAL_PLACES: 100 });`
