### ISSUE TITLE
[QUESTION] Trying to multiply with more significant digits returns 0

### ISSUE THREAD

**Issue by pisomanik** [MikeMcl/bignumber.js#330]
This is the calc I'm trying to replicate using the library 
```
4.035226259175442e+25 * 10**-24 = 40.3522..
```

```js
new Big(4.035226259175442e+25).mul(new Big(10).pow(-24)) // This returns 0
new Big(4.035226259175442e+25).mul(new Big(10).pow(-21)) // THIS WORKS! Returns 4035.. something
```

Am I doing something wrong? Is there a limit on the max numbers that I can use? Any pointers will help. Thank you!

**Comment by shuckster** [comment]
You need to work with [strings, not numbers](https://github.com/MikeMcl/bignumber.js/issues/326#issuecomment-1106481631).

**Comment by MikeMcl** [comment]
For starters, you're in the wrong repo. I assume you're using *big.js* not *bignumber.js*.

Anyway, [here's](http://mikemcl.github.io/big.js/#pow) a pointer to the `pow` documentation. You should be able to work it out from there. 

Hint: you need to change `Big.DP`. 

And, yes, you should be passing numbers with more than a few digits as strings.

**Comment by pisomanik** [comment]
Apologies. I should have written the explicit code. I did change the necessary methods calls to suit this library. 
Thanks for your help :+1:
