### ISSUE TITLE
toFormat method does not exist

### ISSUE THREAD

**Issue by sif-baldr** [MikeMcl/bignumber.js#331]
I tried the basic example among others:

```
y = new BigNumber('1234567.898765')
y.toFormat(2) 

```

I get the following error each time even though the value is a BigNumber:

_Uncaught (in promise) TypeError: y.toFormat is not a function_

**Comment by MikeMcl** [comment]
Perhaps you're using an earlier version of this library.

You have not provided enough information for me to assist further. Closing.
