### ISSUE TITLE
BigNumber.config() typescript error

### ISSUE THREAD

**Issue by lukaw3d** [MikeMcl/bignumber.js#334]
`BigNumber.config().DECIMAL_PLACES` throws `Expected 1 arguments, but got 0.` in typescript

https://github.com/MikeMcl/bignumber.js/blob/d87c6606f905668445b1f5782f94adf8c02c4618/bignumber.d.ts#L1650-L1652 https://github.com/MikeMcl/bignumber.js/blob/d87c6606f905668445b1f5782f94adf8c02c4618/bignumber.d.ts#L1827-L1829

Should be
```ts
   static config(object: BigNumber.Config): BigNumber.Config; 
   static config(): BigNumber.Config;

   static set(object: BigNumber.Config): BigNumber.Config; 
   static set(): BigNumber.Config;
```

**Comment by MikeMcl** [comment]
Yes, the argument should be optional. 

```js
static config(object?: BigNumber.Config): BigNumber.Config; 
```

Thanks for the feedback.
