### ISSUE TITLE
BigNumber.js with very long prime numbers

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [MikeMcl/bignumber.js#337]
Is it possible to manipulate very long prime number from 1k to 2MB long?
I would like to develop a prime number research application, thanks

**Comment by ROBERT-MCDOWELL** [comment]
@MikeMcl why to close without to answer? thanks

**Comment by MikeMcl** [comment]
Hi. Because it isn't an legitimate issue and the question isn't clear enough.

**Comment by ROBERT-MCDOWELL** [comment]
to be more clear is BigNumber.js can deal with prime numbers of more than 2MB or does it need a lot of CPU to manage it?

**Comment by ROBERT-MCDOWELL** [comment]
I use also my free time for research.... thanks for your kindness..
