### ISSUE TITLE
NaN raised to a power of zero returns 1 (not NaN)

### ISSUE THREAD

**Issue by Kolobamanacas** [MikeMcl/bignumber.js#340]
Repro steps:

``` typescript
import BigNumber from "bignumber.js";

const number = new BigNumber('1 Definitely 2 not 3 a 4 number 5').exponentiatedBy(new BigNumber('0'));

console.log(number.toString()); // Prints 1 (not NaN).
console.log(number.toFixed()); // Prints 1 (not NaN).
```

I'm not sure whether this behavior is intentional or not, but it seems to me that any arithmetical operation including not-a-number must return not-a-number. Getting "1" creates false impression that operation is valid and was performed using valid operands, which, in my opinion, is not the case with not-a-numbers.

**Comment by MikeMcl** [comment]
Whether it would be better to return NaN is a moot point here as the power operation intentionally defers to `Math.pow`:

```js
Math.pow(NaN, 0)    // 1
```

**Comment by Kolobamanacas** [comment]
Hmm, I see. I wasn't aware of this Math's behavior, thanks. I don't think it's correct either, but I guess it's not the place from where we could change it. :)
