### ISSUE TITLE
Strangeness in "minimum" method

### ISSUE THREAD

**Issue by iKBAHT** [MikeMcl/bignumber.js#344]
Actual:
`BigNumber.minimum(0, -0)` is `0`

Expected
`BigNumber.minimum(0, -0)` is `-0`

Interesting that `BigNumber.minimum(-0, 0)` works just expected (`-0`)

Online [exampe](https://codesandbox.io/s/bignumber-js-forked-zknjji?file=/src/index.js)

**Comment by MikeMcl** [comment]
Good find.
I should have had a test case checking that. No doubt `maximum` has the same issue.
I'll apply a fix presently.
Thank you for the report.

**Comment by MikeMcl** [comment]
Fixed in *v9.1.2*.
