### ISSUE TITLE
Division on exponential values leads to infinite loop

### ISSUE THREAD

**Issue by sfc-gh-aananthanarayanan** [MikeMcl/bignumber.js#347]
TL;DR - `.div` API on BigNumber instance on very small numbers leads to infinite loop.

Example code:

```Javascript
let num = new BigNumber(1e-20);

for(let i = 0; i< 1000 ; i++) {
	num = num.div(2);
}

console.log('number: ', num.toString());
```

At the end the loop `num` is still `1e-20`. Expected `(new BigNumber(1e-20)).div(2)` to be `5e-21`.

Is this expected? If so apart from having circuit breakers on loops is there any other safe way to end this?

**Comment by shuckster** [comment]
What's your [DECIMAL_PLACES](https://mikemcl.github.io/bignumber.js/#decimal-places) setting?

**Comment by sfc-gh-aananthanarayanan** [comment]
```BigNumber.set({ DECIMAL_PLACES: 308 });```

Right now it is set to 308

**Comment by MikeMcl** [comment]
If it was set to `308` you would end up with `1e-308`, if it was set to `20` you would end up with `1e20`.

I don't see an issue here.
