### ISSUE TITLE
Looks like the changelog has a lot of unmarked breaking changes

### ISSUE THREAD

**Issue by saintech** [MikeMcl/bignumber.js#349]
Hi. I updated bignumber.js in an old project and got a lot of errors about methods that don't exist like ".lessThan", ".sub", ".add" etc. But there is nothing similar in the changelog items marked as breaking changes.

**Comment by shuckster** [comment]
Which version did you migrate from and to?

**Comment by shuckster** [comment]
Looks like [6.0.0](https://github.com/MikeMcl/bignumber.js/blob/v6.0.0/bignumber.js) is the first version to remove the alias `lessThan`. I didn't check the others.

**Comment by saintech** [comment]
@MikeMcl yea, that's what I was talking about - some changes are marked as "breaking" and some are not. I made many migrations through the years and major versions, and this library is the first where i met this problem.

<sub>p.s.: i know about semver, thank you, but it is not related to the issue</sub>
