### ISSUE TITLE
[Feature Request]: Can we support `toBigInt`?

### ISSUE THREAD

**Issue by Dunqing** [MikeMcl/bignumber.js#352]
[BigInt Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)

**Comment by dsldsl** [comment]
I would also like this. Would be open to contributing a PR if you can provide some context @MikeMcl and its something that makes sense. 

FYI, I notice that using BigInt(bigNumber.toString()) has some precision loss.  Is there another suggest way in the meantime?
