### ISSUE TITLE
Minus sign in formatted strings

### ISSUE THREAD

**Issue by szgabsz91** [MikeMcl/bignumber.js#357]
The following methods format the `BigNumber` instance into a string:

* `toExponential`
* `toFixed`
* `toFormat`
* `toJSON`
* `toPrecision`
* `toString`
* `valueOf`

If the `BigNumber` instance is negative, these methods use the U+002D character ([hyphen-minus](https://www.compart.com/en/unicode/U+002d)) as the minus sign.

However, if I'm correct, it would be better to use the U+2212 character ([minus sign](https://www.compart.com/en/unicode/U+2212)), as it is visually and semantically a better option for this use case.

If this change request is accepted, I think I could also provide a PR if it helps.

Thank you!

**Comment by MikeMcl** [comment]
Interesting, but the JavaScript parser doesn't recognise it appropiately so it doesn't seem practical to make the change.

```js
const log = console.log;

log(Number('\u22123'))     // NaN
log(Number('−3'))          // NaN

log(Number('\u002d3'))     // -3
log(Number('-3'))          // -3
```

**Comment by szgabsz91** [comment]
I didn't know that the output of these methods need to be handled correctly by the `Number` constructor, but if this is a requirement, then I guess this will remain as it is. Thanks for the quick answer!
