### ISSUE TITLE
Is there any other way to handle new BigNumber(999999999999999999999) without using strings？

### ISSUE THREAD

**Issue by Usualminds** [MikeMcl/bignumber.js#362]
- as we know, 999999999999999999999 is greater than Number.MAX_SAFE_INTEGER， so it will be imprecise
- use js: Number(9999999999999999) = 10000000000000000; String(9999999999999999) = '10000000000000000'
- use bigint  : Number(9999999999999999n) = 9999999999999999 ; String(9999999999999999n) = '9999999999999999'

The question is if we want to deal with large numbers like 999999999999999999999, **can we ensure that its precision is not lost if we use any other JavaScript method**?

Or we can only rely on the server to return a string instead of a number to handle this situation.

**Comment by shuckster** [comment]
When using Number, the precision is lost on construction.

There's no way to get a precise answer from a value that hits either UNSAFE or BFP limitations, because that precision cannot be stored in the first place.

If you wish to work with such numbers, you must use strings for both serialisation and business logic.

**Comment by MikeMcl** [comment]
@Usualminds 

If you are asking if there is another way to transmit a big integer over a network without sending it as a string, then the answer is yes you can send it more compactly as an array of bytes.

You can convert a number, BigInt or BigNumber to binary or better hexdecimal, using `.toString(16)`, then convert that to a array of bytes by filling a `Uint8Array` using `parseInt(hex, 16)` on each two hexadecimal characters. Is that the sort of thing you require?
