### ISSUE TITLE
toString() default base is not 10?

### ISSUE THREAD

**Issue by 0x33dm** [MikeMcl/bignumber.js#372]
I see [in the documentation](https://mikemcl.github.io/bignumber.js/#toS) that .toString() is supposed to be base 10, but when I test it on my application, the default isn't base 10.

Tested on google chrome with version 9.1.2

```ts
    console.log( BigNumber(10000000000000000000000).toString() ) //1e+22 
    console.log( BigNumber(10000000000000000000000).toString(10) ) // 10000000000000000000000
```

**Comment by MikeMcl** [comment]
`1e+22` is the value in base 10, in exponential notation. The documentation at your link states:

> If a base is not specified... then exponential notation is returned.

`1e+22` means `1 x 10**22`, which is the same as `10000000000000000000000`.

**Comment by 0x33dm** [comment]
> `1e+22` is the value in base 10, in exponential notation. The documentation at your link states:
> 
> > If a base is not specified... then exponential notation is returned.
> 
> `1e+22` means `1 x 10**22`, which is the same as `10000000000000000000000`.

I missed that. Thank you
