### ISSUE TITLE
performance of pow function

### ISSUE THREAD

**Issue by rbro** [MikeMcl/bignumber.js#38]
I am using bignumber.js for financial calculations, and I noticed that the pow() function can be slow at times.  For example, the below takes 4 seconds to execute:

var a = new BigNumber(1.0011012345678).pow(-2000);

Is this expected?  If so, are there things that I can do to speed up calculations like this?  I know one option is to round to fewer digits before running the pow function, but are there others?

As a comparison, I also use bcmath in PHP, and I noticed the bcpow function returns instantly for the above calculation:

$a = bcpow(1.0011012345678, -2000);

Thanks for your help.

Ryan

**Comment by MikeMcl** [comment]
Added a `POW_PRECISION` configuration option in v2.0.1, so the number of significant digits calculated by the power operation can be limited. This has greatly improved its performance.

**Comment by michaelessiet** [comment]
Thanks @MikeMcl , `decimal.js` did the trick
