### ISSUE TITLE
Add missing bower.json

### ISSUE THREAD

**Issue by devantoine** [MikeMcl/bignumber.js#42]
Adding the missing bower.json would be very nice to work with bower. It can download the project but it's not able to know which file to include, which is the exact purpose of the "main" property of the bower.json.

For more infos on how to do it, refer to the following issue: https://github.com/CreateJS/SoundJS/issues/76

**Comment by nicolaes** [comment]
Had the same problem with bower.json's "main" property. Our scripts rely on that property to build the project - similar with what @metaman described.
Unfortunately we had to rely on big.js but the development is hindered due to it's reduced feature set.
Would love to see an update on this.

**Comment by MikeMcl** [comment]
@nicolaes Okay, I'll add a bower.json tomorrow.

**Comment by nicolaes** [comment]
Thanks @MikeMcl .
As bower automatic dependencies are almost always used with build scripts that include minification I suggest going with *"main": "bignumber.js"* - as you did in the big.js library :)
If there is need I can also lend a hand with the development around, by the way.

**Comment by MikeMcl** [comment]
bower.json added in v2.0.6
