### ISSUE TITLE
toFraction() behavior

### ISSUE THREAD

**Issue by markletp** [MikeMcl/bignumber.js#48]
Best described by example

http://jsfiddle.net/a6t784am/2/

.toFraction() seems to land on a denominator based around the DECIMAL_PLACES config variable when a MaxD is not supplied. A MaxD in range of a known denominator give the correct solution.

**Comment by MikeMcl** [comment]
The behaviour is as expected. 

When you call `toFraction`, you are calling it on the number `3.08218318695106649937`, not on the rational number `4913/1594` (which cannot be stored as a BigNumber as it has a non-terminating decimal expansion). 
To clarify:

    var BN = BigNumber; 
    BN.config(20);
    var n = BN(4913).div(1594);

    n.toString();    // 3.08218318695106649937
    n.toFraction()    // [ "308218318695106649937", "100000000000000000000" ]

    BN.config(10);
    n = BN(4913).div(1594);

    n.toString();    // 3.082183187
    n.toFraction()    // [ "3082183187", "1000000000" ]

Do you follow?

**Comment by markletp** [comment]
Thanks for the quick response Mike. I understand how it applies now. I'll have to track the rational expression separately. 

Cheers, 

-Thomas
