### ISSUE TITLE
FAQ in documentation is stale/incorrect

### ISSUE THREAD

**Issue by f3ndot** [MikeMcl/bignumber.js#51]
In the *Why are trailing fractional zeros removed from BigNumbers?* section:

```js
x = new BigDecimal("1.0")
y = new BigDecimal("1.1000")
z = x.add(y)                      // 2.1000

x = new BigDecimal("1.20")
y = new BigDecimal("3.45000")
z = x.multiply(y)                 // 4.1400000
```

should be 

```js
x = new BigNumber("1.0")
y = new BigNumber("1.1000")
z = x.plus(y)                      // 2.1000

x = new BigNumber("1.20")
y = new BigNumber("3.45000")
z = x.times(y)                 // 4.1400000
```

**Comment by f3ndot** [comment]
Also I guess it would be most correct to be called *BigNumber* in the section title

**Comment by MikeMcl** [comment]
No, the FAQ is not stale or incorrect.

No, `new  BigDecimal` should not be `new BIgNumber`.

The code example I gave shows the actual behaviour of "many arbitrary-precision libraries", i.e. Java's BigDecimal. 

The code example you offer in replacement is incorrect and is not how the bignumber.js behaves - trailing zeros are not preserved, that is the whole point of the piece.
