### ISSUE TITLE
Source map file is missing on CDNJS

### ISSUE THREAD

**Issue by projected1** [MikeMcl/bignumber.js#55]
Linking to "//cdnjs.cloudflare.com/ajax/libs/bignumber.js/2.0.3/bignumber.min.js" will lead to this error:
*"GET //cdnjs.cloudflare.com/ajax/libs/bignumber.js/2.0.3/doc/bignumber.js.map 404 (Not Found)".*

Please upload the source map file to CDNJS.

It would also be helpful to have an "pretty" version of this lib on CDNJS, even that we have a source map file.

**Comment by MikeMcl** [comment]
As far as I know, [cdnjs](https://cdnjs.com/) just hosts a single minified file for each library version, and I've just tried [https://cdnjs.cloudflare.com/ajax/libs/bignumber.js/2.0.3/bignumber.min.js](https://cdnjs.cloudflare.com/ajax/libs/bignumber.js/2.0.3/bignumber.min.js) and it loads without a problem.

**Comment by josdejong** [comment]
You can go wild and publish as many files as you like on cdnjs. Many libraries nowadays provide three files: a full `*.js` file, a minified `*.min.js` file, and a corresponding `*.map` file, see for example:

http://cdnjs.com/libraries/jquery
http://cdnjs.com/libraries/underscore

**Comment by MikeMcl** [comment]
Oh, I see. Then again, they are two of the most important JS libraries out there.

Personally, I'm not going to make a pull request to [cdnjs](https://github.com/cdnjs/cdnjs) for the inclusion of the source map and non-minified version of this library, but anyone else is welcome to do so.

**Comment by josdejong** [comment]
It wasn't hard, the pre-conditions are described in the readme. If you create a package.json file containing a description of which files to copy, the updates can be done automatically from then on (see https://github.com/cdnjs/cdnjs#enabling-npm-auto-update). Here is the package.json file of math.js: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/mathjs/package.json.

**Comment by MikeMcl** [comment]
Thanks, Jos.

**Comment by MikeMcl** [comment]
Submitted [pull request](https://github.com/cdnjs/cdnjs/pull/4508) adding source map and non-minifed version.
