### ISSUE TITLE
ios 8 problem

### ISSUE THREAD

**Issue by ramarro123** [MikeMcl/bignumber.js#57]
hello,

this snippet of code doesn't work with ios8

        <script>
            var a = new BigNumber(0.5);
            var b = new BigNumber(0.5);
            a = a.plus(b);
            console.log(+a);
        </script>

console.log print NaN

with a bit of debug i found that the problem is here
xc[b] %= BASE;

here log of safari console
> xc[b]
< 100000000000000
> BASE
< 100000000000000
> xc[b] % BASE
< 2.5333397e-315
> a % 1
< 0
> 1 % 1
< 0

note the 2.5333397e-315 as a result of mod operation....
seems a safari bug, but as you know, it's easy if your lib support browser os rather than ask to steve jobs (rest in peace) to fix safari in the next ios version :dancers: 

for now my (hugly) fix is
                if (BASE == xc[b])
                    xc[b] = 0;
                else  
                    xc[b] %= BASE;

in "plus" function

**Comment by MikeMcl** [comment]
How strange. Unfortunately, I can not try it myself at the moment.

What does `1e14 % 1e14` produce in the console?

Please post the result of adding `console.dir(a)` to your snippet so I can see the `c`, `e` and `s` properties of `a`.

**Comment by ramarro123** [comment]
modified the code as follow
<script>
    var a = new BigNumber(0.5);
    var b = new BigNumber(0.5);
    a = a.plus(b);

    console.log("printing +a");
    console.log(+a);

    console.log("printing console.dir(a)");
    console.dir(a);


    console.log("printing 1e1%1e1");
    console.log(1e1 % 1e1);

    console.log("printing 1e5%1e5");
    console.log(1e5 % 1e5);

    console.log("printing 1e7%1e7");
    console.log(1e7 % 1e7);

    console.log("printing 1e8%1e8");
    console.log(1e8 % 1e8);

    console.log("printing 1e9%1e9");
    console.log(1e9 % 1e9);

    console.log("printing 1e10%1e10");
    console.log(1e10 % 1e10);

    console.log("printing 1e11%1e11");
    console.log(1e11 % 1e11);

    console.log("printing 1e12%1e12");
    console.log(1e12 % 1e12);

    console.log("printing 1e13%1e13");
    console.log(1e13 % 1e13);

    console.log("printing 1e14%1e14");
    console.log(1e14 % 1e14);


    console.log("printing 1e15%1e15");
    console.log(1e15 % 1e15);

</script>

output: (i have try to 'beautify' the report)
---------------------------------------------------------------- KO (a is NaN)
[Log] printing +a (test.html, line 10)
[Log] NaN (test.html, line 11)
---------------------------------------------------------------- KO (please note c[1])
[Log] printing console.dir(a) (test.html, line 13)
[Log] BigNumber (test.html, line 14)
c: Array[2]
0: 1
1: 2.5333397e-315
length: 2
__proto__: Array[0]
e: 0
s: 1
__proto__: BigNumber
---------------------------------------------------------------- OK
[Log] printing 1e1%1e1 (test.html, line 17)
[Log] 0 (test.html, line 18)
---------------------------------------------------------------- OK
[Log] printing 1e5%1e5 (test.html, line 20)
[Log] 0 (test.html, line 21)
---------------------------------------------------------------- OK
[Log] printing 1e7%1e7 (test.html, line 23)
[Log] 0 (test.html, line 24)
---------------------------------------------------------------- OK
[Log] printing 1e8%1e8 (test.html, line 26)
[Log] 0 (test.html, line 27)
---------------------------------------------------------------- OK
[Log] printing 1e9%1e9 (test.html, line 29)
[Log] 0 (test.html, line 30)
---------------------------------------------------------------- KO!!!
[Log] printing 1e10%1e10 (test.html, line 32)
[Log] 2.65249474e-315 (test.html, line 33)
---------------------------------------------------------------- KO!!!
[Log] printing 1e11%1e11 (test.html, line 35)
[Log] 1.9230586856e-314 (test.html, line 36)
---------------------------------------------------------------- KO!!!
[Log] printing 1e12%1e12 (test.html, line 38)
[Log] 1.3428254615e-314 (test.html, line 39)
---------------------------------------------------------------- KO!!!
[Log] printing 1e13%1e13 (test.html, line 41)
[Log] 1.900263809e-314 (test.html, line 42)
---------------------------------------------------------------- KO!!!
[Log] printing 1e14%1e14 (test.html, line 44)
[Log] 2.5333397e-315 (test.html, line 45)
---------------------------------------------------------------- KO!!!
[Log] printing 1e15%1e15 (test.html, line 48)
[Log] 3.166674627e-315 (test.html, line 49)

**Comment by MikeMcl** [comment]
Thanks.

It looks like the `%` operator has problems with operands over 32 bits, which seems to be a surprisingly rudimentary failing of the JavaScript implementation.

I am reluctant to apply a fix to work round it here at this stage, but further details/confirmation of this issue would be welcome.

**Comment by ramarro123** [comment]
if you can share the snippet code with the fix, i will apply it locally eventually.
this issue unfortunatly prevent me to use this lib, as i work in mobile env.

I don't think that my fix is correct, probably it will be not too much fork for you to put out a fix for that, even locally or in a special version

**Comment by MikeMcl** [comment]
What are the results given for each of the following?
    
    1 % 1e14
    2147483647 % 1e14
    2147483648 % 1e14
    4294967295 % 1e14     
    4294967296 % 1e14

**Comment by ramarro123** [comment]
here we go

[Log] printing 1 % 1e14 (test.html, line 17)
[Log] 1 (test.html, line 18)
[Log] printing 2147483647 % 1e14 (test.html, line 20)
[Log] 2147483647 (test.html, line 21)
[Log] printing 2147483648 % 1e14 (test.html, line 23)
[Log] 2147483648 (test.html, line 24)
[Log] printing 4294967295 % 1e14 (test.html, line 26)
[Log] 4294967295 (test.html, line 27)
[Log] printing 4294967296 % 1e14 (test.html, line 29)
[Log] 4294967296 (test.html, line 30)

**Comment by ramarro123** [comment]
code modified as follow

    console.log("printing 1 % 1e14");
    console.log(1 % 1e14);

    console.log("printing 2147483647 % 1e14");
    console.log(2147483647 % 1e14);

    console.log("printing 2147483648 % 1e14");
    console.log(2147483648 % 1e14);

    console.log("printing 4294967295 % 1e14");
    console.log(4294967295 % 1e14);

    console.log("printing 4294967296 % 1e14");
    console.log(4294967296 % 1e14);

**Comment by MikeMcl** [comment]
Oh, so it just seems to fail when the first operand equals the second operand.

    1e14 % 1e14        // 2.5333397e-315 fail
    (1e14+1) % 1e14    // 1 okay
    (1e14-1) % 1e14    // 99999999999999 okay  

Is that correct?

**Comment by ramarro123** [comment]
confirmed!!

[Log] printing 1e14 % 1e14 (test.html, line 17)
[Log] 2.5333397e-315 (test.html, line 18)
[Log] printing (1e14+1) % 1e14 (test.html, line 20)
[Log] 1 (test.html, line 21)
[Log] printing (1e14-1) % 1e14 (test.html, line 23)
[Log] 99999999999999 (test.html, line 24)

**Comment by MikeMcl** [comment]
Your fix is correct then.

[https://developer.apple.com/bug-reporting/](https://developer.apple.com/bug-reporting/)
