### ISSUE TITLE
attempting to invert a number runs out of memory

### ISSUE THREAD

**Issue by shekenahglory** [MikeMcl/bignumber.js#58]
new BigNumber('0.50000025000012500006').pow(-1).toString()

this should work right? trying to invert the number.

after about 15 seconds I get: 
FATAL ERROR: JS Allocation failed - process out of memory
Abort trap: 6

on node.js, version 2.0.3

**Comment by shekenahglory** [comment]
same error for new BigNumber(1).dividedBy('0.50000025000012500006').toString();

**Comment by MikeMcl** [comment]
Fixed in v2.0.4 by e7e7e08.

It was a critical and disappointing bug in the division operation, affecting all 2.x.x versions.

Thanks very much for the report.
