### ISSUE TITLE
tag 1.4.1 deleted

### ISSUE THREAD

**Issue by adrianboimvaser** [MikeMcl/bignumber.js#59]
I was using "bignumber.js": "~1.4.1" in my bower.json file. I looks like the 1.4.x tags were deleted and now bower complains with "ENORESTARGET No tag found that was able to satisfy ~1.4.1". Please keep the tags going forward.

**Comment by MikeMcl** [comment]
I'm sorry, I didn't realise that deleting some older tags would cause this problem.  I won't delete them in future.

**Comment by adrianboimvaser** [comment]
Thank you.

**Comment by adrianboimvaser** [comment]
Any chance you could restore the tag?

**Comment by MikeMcl** [comment]
Yes, it's done.

**Comment by adrianboimvaser** [comment]
Much appreciated.
