### ISSUE TITLE
Option for "Engineering notation" - With toExponential()

### ISSUE THREAD

**Issue by mgkr** [MikeMcl/bignumber.js#61]
Engineering notation: "the powers of ten must be multiples of three".

It would be nice to have the ability to output 12356 as 12.345e+3, instead of 1.23456e+5.

Either as it's own method toEngineering() - Identical to toExponential() except for the "multiples of three" bit.

OR

As an extra parameter(\*) to toExponential()
(*) Which perhaps could then allow an arbitrary multiple (not just 3)

And if it was possible to query a BigNumber for this "Engineering" exponent as well (similar to BN.e) that would be an extra bonus

**Comment by MikeMcl** [comment]
Well, I like `toEngineering`, but as engineering notation is a form of exponential notation it seems appropiate to handle it using `toExponential`. 

The problem is that `toExponential` already takes a rounding mode as a second argument, and I don't want any methods here to have more than two parameters.

That leaves the option of using `BigNumber.config`. For example,

```javascript
var n = new BigNumber(123);
n.toExponential();    // '1.23e+2'

BigNumber.config({ ENGINEERING: true });
n.toExponential();    // '0.123e+3'
```

**Comment by mgkr** [comment]
That (using config) might work.
Instead of a bool though, why not an integer - So one would have the chance of going multiples of 6 (or whatever) as well. 
Very niche case if any would ever need that (I don't think I ever would).
But if making the change, it ought to be negligible to allow for an int setting over just a bool, so no reason to limit it imo.

**Comment by MikeMcl** [comment]
Yes, I was wondering how values less than 1000 should be properly handled, but having `toExponential` return numbers without an exponent doesn't seem appropiate.

On second thoughts I think using `toEngineering` would be best, though not with an arbitrary multiple. 

I think its a good suggestion and I'll put in on my to-do list and close for now.
