### ISSUE TITLE
Removing of tags

### ISSUE THREAD

**Issue by travisperson** [MikeMcl/bignumber.js#62]
I was curious why some tags have been deleted. Is there a particular reason to clean up and remove previous tags or was it unintentional? 

I was previously using a tag to `v1.2.0` in a bower file, upgrading to `v1.4.1` isn't an issue luckily.

**Comment by MikeMcl** [comment]
It was just the inclination to pare down overcoming the inclination to conserve.
I am open to requests to restore a specific tag, but I see that in this case it is not necessary.
