### ISSUE TITLE
Why not define Rounding: Decimal Places at BigNumber.config?

### ISSUE THREAD

**Issue by nottinhill** [MikeMcl/bignumber.js#65]
First, thanks for this excellent library, much appreciated. I am using it in a financial application and it works great to far. I have the following issue, this is how I use `BigNumber.config`:

    BigNumber.config({ DECIMAL_PLACES: 10 });
    BigNumber.config(null, BigNumber.ROUND_HALF_UP):
    var ROUNDING_DP = 8

This is how I instantiate:

    value = new BigNumber value;
    value.toFixed(ROUNDING_DP);

From my understanding the `toFixed` method takes *only* the `ROUND_HALF_UP`property from the .config. Wouldn't it be convenient to be able to also do:

    BigNumber.config(null, BigNumber.ROUND_HALF_UP, BigNumber.ROUNDING_DP)

and then just:

    value.toFixed()

**Comment by MikeMcl** [comment]
Rather than

    BigNumber.config({ DECIMAL_PLACES: 10 });
    BigNumber.config(null, BigNumber.ROUND_HALF_UP):

you can use

    BigNumber.config({ DECIMAL_PLACES: 10, ROUNDING_MODE: BigNumber.ROUND_HALF_UP });

or

    BigNumber.config(10, BigNumber.ROUND_HALF_UP);

or just

     BigNumber.config(10, 4);

Anyway, #22 discusses the behaviour of `toFixed()`, and I don't see much to be gained from having a `ROUNDING_DP` setting that applies to it and also presumably to `toExponential` and `toPrecision`. 

Incidentally, you can also pass a rounding mode to those methods, for example

    value.toFixed(8, BigNumber.ROUND_DOWN);

or

   value.toFixed(8, 1);

Thanks for the feedback.

**Comment by nottinhill** [comment]
My application is huge and it would be very convenient for me to change dp centrally like you like the convenience of changing rm globally.

See in my opinion 

> if dp is omitted, or is null or undefined, the return value is n rounded to a whole number.
> if rm is omitted, or is null or undefined, ROUNDING_MODE is used.

it should say the same for dp. *if dp is omitted or is null or undefined, ROUNDING_DP is used, if not set, the return value is n rounded to a whole number*.

In addition to being more streamlined and coherent this way, I just dont see much financial nor science application that would want to use *BigNumber* for the sake of using integers without floating point (whole numbers) which by default is handled pretty well by binary arithmetics last time I checked. 

Also to conclude my rambling about coherence, why did you introduce syntax like **.config(10,4)**? In my opinion the entropy of such syntax converges towards zero.

Hope you can stand critisism, don't mistake it for a lack of gratitude for your work, which it isn't. :-)

**Comment by MikeMcl** [comment]
I apologise if you were offended my my quick closing.

The methods which could use a global `ROUNDING_DP` setting if no arguments were passed, already have default behaviour that I think is useful.

If, as you suggest, the `round` method used `ROUNDING_DP` if no argument was passed, then that would break compatibility with JavaScript's `Math.round` which rounds to an integer.

Similarly, the link I posted above explains that calling `toFixed` without any arguments is useful for when `toString` returns exponential notation and the user wants fixed-point notation but no rounding.

The `config(10, 4)` syntax was kept in for backwards compatibility, and it's a lot less verbose.

Criticism of the library and its API is encouraged, and you are welcome to explain or justify your position further.
