### ISSUE TITLE
Got 404 with bower install

### ISSUE THREAD

**Issue by lisposter** [MikeMcl/bignumber.js#66]
I install it using bower in my Mac, and serve my sites in vagrant based linux server, and using symlink to share the code between Mac and Linux. and then I got a 404 from nginx in linux server.

```
2015/04/20 04:58:26 [error] 3133#0: *1 open() "/vagrant/site/www/vendor/bignumber.js/bignumber.js" failed (20: Not a directory), client: 192.168.211.1, server: mydomain, request: "GET /vendor/bignumber.js/bignumber.js HTTP/1.1", host: "mydomain"
```

I figure it out, there are two ways to solve this:

- Install this dep with bower inside my linux server
- Rename the directory name from `bignumber.js` to `bignumber`

I didn't know, if this is an bower issue or just because the filesystem' difference between Mac OS and Linux.

If it is not a bower issue, maybe we should consider to make a alias for bower.

**Comment by MikeMcl** [comment]
Perhaps somoeone else has some useful input here. I don't.

**Comment by josdejong** [comment]
If you can successfully install, open, and rename the directory `bignumber.js` on your system then I suppose it's no issue with bower and no issue with your filesystem.

**Comment by lisposter** [comment]
It's seems not in common, and I think it will not happened in production env. May be just because the OS X treated the `bignumber.js` dir as a file, and add something info to somewhere. So when I shared this dir with Linux by symlink, it lead to this.

If nobody know why or nobody else report this, you can ignore it.
