### ISSUE TITLE
Did you just delete all tags before 1.4?

### ISSUE THREAD

**Issue by kumarharsh** [MikeMcl/bignumber.js#67]
I've started getting errors on bower install. I checked the tags page, and all old tags (versions mentioned in the change log) are wiped away.

This can lead to some problems for projects which depend on older versions of bignumber. Can you fix this issue?

**Comment by MikeMcl** [comment]
No, it was done some weeks ago. See #59.

I have now restored all the tags.

**Comment by kumarharsh** [comment]
Thanks!
Oh, and I apologize for the tone of my phrasing of the issue. I may have been too shocked at that time :-)
