### ISSUE TITLE
Floating point rounding

### ISSUE THREAD

**Issue by GerhardLiebenberg** [MikeMcl/bignumber.js#69]
Hi
In the "toFormat" example rounding takes place in the decimals:
y = new BigNumber('1234567.898765')
y.toFormat(2) // "1,234,567.90"

But the whole idea of using a library like bignumber.js is to avoid floating point rounding errors. 
How would you format a currency value to always have two decimals - but to truncate excess decimals instead of performing rounding?

**Comment by richardaday** [comment]
+1

`toFormat` is currently respecting the `ROUNDING_MODE` property.  For example, the below would work:

```
BigNumber.config({ROUNDING_MODE: BigNumber.ROUND_FLOOR});
y = new BigNumber('1234567.898765')
y.toFormat(2) // "1,234,567.89"
```

However, it seems there is no way to do that without having to change the global configuraton of rounding.

Question 1: Can we extend the `floor` method to take in a decimal place to round to?  Currently the `floor` method always returns a whole number, which is not always what the consumer wants.  It would look like:

```
y = new BigNumber('1234567.898765')
y.floor(2) // "1,234,567.89"
```

Question 2: What's the difference between the `floor` method and `truncated`?  It seems like they do the same thing.

**Comment by MikeMcl** [comment]
@GerhardLiebenberg 

You can either change the global rounding mode 

    BigNumber.config({ROUNDING_MODE: BigNumber.ROUND_DOWN});

 or, as `toFormat` accepts an optional rounding mode you could use

    y = new BigNumber('1234567.898765');
    y.toFormat(2, BigNumber.ROUND_DOWN);   // '1,234,567.89'
    y.toFormat(2, 1);                      // '1,234,567.89'

`ROUND_DOWN` rounds towards zero, so positive and negative values will be truncated.

@richardaday 

1.
`round` can be used to truncate to a specififc number of decimal places, e.g.

y = new BigNumber('1234567.898765');
y.round(2, BigNumber.ROUND_DOWN);    // "1,234,567.89"

2.
`floor` rounds toward negative infinity, `trunc` rounds up or down towards zero. 
If a value is positive, they are equivalent.

**Comment by richardaday** [comment]
I did look through the documentation, but must have overlooked looking at the method signature for toFormat --- I see that it is there.  Thanks for the clarification!

**Comment by GerhardLiebenberg** [comment]
Thank you guys. That should do the trick.
