### ISSUE TITLE
Is there any way to calculate the cubic root of a BigNumber object ?

### ISSUE THREAD

**Issue by Moligaloo** [MikeMcl/bignumber.js#72]
I found there is no method similar Math.cbrt (cubic root of a float), and the parameter of method pow() only allow integer, then I can not use pow(1/3) to calculate the cubic root.

**Comment by MikeMcl** [comment]
[decimal.js](https://github.com/MikeMcl/decimal.js) supports non-integer powers, and a `cbrt` method may be added soon.
