### ISSUE TITLE
Bug: Failure on integers greater than 41 bytes in length

### ISSUE THREAD

**Issue by CoryGH** [MikeMcl/bignumber.js#74]
This is probably best described with an example:

    function tester(bytes) {
        var b = new BigNumber(2);
        b = b.toPower(bytes * 8);
        var t = b.toString(16).toUpperCase();
        b = b.minus(1);
        var h = b.toString(16).toUpperCase();
        var good = true;
        if (t[0] != '1') good = false;
        if ((h.length / 2) != bytes) good = false;
        if (good) for (var i = 1; i < t.length; i++) { if (t[i] != '0') good = false; }
        if (good) for (var i = 0; i < h.length; i++) { if (h[i] != 'F') good = false; }
        document.write(bytes + ': ' + (good ? 'pass' : 'fail') + '<br />' + t + '<br />' + h + '<br />');
    }
    tester(40);
    tester(41);
    tester(42);
    tester(43);

Output:

    40: pass
    100000000000000000000000000000000000000000000000000000000000000000000000000000000
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    41: pass
    10000000000000000000000000000000000000000000000000000000000000000000000000000000000
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    42: fail
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDC
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDB
    43: fail
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF690
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF68F

Fiddle: http://jsfiddle.net/24usrq0a/

Edit: Upon further inspection this appears to be related to the .toPower() function, when initializing the BigNumber() pseudoclass with the full hex string in base-16 it does load and output correctly otherwise. http://jsfiddle.net/sf6jnn74/

**Comment by MikeMcl** [comment]
This isn't a bug. The base conversion isn't being performed on the values assumed.

By default the precision of the power operation is set at 100 significant digits.

See http://mikemcl.github.io/bignumber.js/#pow

To ensure the power operation operates at unlimited precision use

    BigNumber.config({ POW_PRECISION: 0 })

```
2.135987035920910082395021706169552114602704522356652769947041607822219725780640550022962086936576e+96
40: pass
100000000000000000000000000000000000000000000000000000000000000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
5.46812681195752981093125556779405341338292357723303109106442651602488249799843980805878294255763456e+98
41: pass
10000000000000000000000000000000000000000000000000000000000000000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
1.39984046386112763159840142535527767382602843577165595931249318810236991948760059086304843329475444736e+101
42: pass
1000000000000000000000000000000000000000000000000000000000000000000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
3.5835915874844867368919076489095108449946327955754392558399825615420669938882575126094039892345713852416e+103
43: pass
100000000000000000000000000000000000000000000000000000000000000000000000000000000000000
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
```

**Comment by CoryGH** [comment]
Ah my mistake, thank you very much for clearing this up.
