### ISSUE TITLE
Feature Request: toString(256)

### ISSUE THREAD

**Issue by CoryGH** [MikeMcl/bignumber.js#75]
Or some toByteArray() equivalent that would output a JavaScript [Uint8Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array#Browser_compatibility) would be even better for [performance](http://jsfiddle.net/x4weLfa6/).

A fromByteArray() equivalent method would also be great to have.

**Comment by MikeMcl** [comment]
I'll consider `toByteArray` and `fromByteArray` but it's not something that would be particularly performant because internally big numbers aren't stored in a base that is a power of two (as they commonly are in big integer libraries). They are stored in base 1e14 (i.e. a power of ten), so its quite a lot of crunching to do the base conversion to or from base 256.

BTW I don't think `s[i] = String.fromCharCode(i);` is doing what you think. You can't set a character of a string like that and unfortunately JS doesn't warn you if you try to.

**Comment by CoryGH** [comment]
Good catch, in case you want to see the functional results of that test: http://jsfiddle.net/x4weLfa6/1/

**Comment by CoryGH** [comment]
Not trying to come off as pushy but I'm curious if you have a general ETA for the `toByteArray` and `fromByteArray` functions?  If it's something that will be some time is there any way you could point me at the parts of the source I should look at to try to implement it myself?

**Comment by MikeMcl** [comment]
I don't want these methods to be added to the library as I don't see much use for them.

While all base 256 numbers can be represented exactly in decimal, most decimal numbers with fraction digits cannot be represented exactly in base 256, so a `toByteArray` method would often produce only an approximation, which seems to me to be of limited value.

I think it was an interesting suggestion and thanks for reminding me to make a decision on this.

**Comment by CoryGH** [comment]
Is there a preferred way to add functionality to the bignumber.js NPM module for node.js that would be expected to work throughout future releases?

**Comment by MikeMcl** [comment]
You can add methods to the prototype, so they can be accessed from any BigNumber instance, for example,

    BigNumber.prototype.toByteArray = function () { /* more code */ };
    var n = new BigNumber(512);
    n.toByteArray();    // [2, 0]

Or you can add methods to a BigNumber constructor, for example

    BigNumber.toByteArray = function (n) { /* more code */ };

I would expect that to work through future releases.

**Comment by CoryGH** [comment]
Thanks, by the way if you want it I rolled some help [from StackOverflow](http://stackoverflow.com/questions/34486516/convert-base-10-and-base-255-integer-strings-in-javascript/) into an [OO Base 2-256 converter that outputs as UInt8Array](https://jsfiddle.net/28nvLaL5/18/).
