### ISSUE TITLE
Enhancement: Preservation of data -0

### ISSUE THREAD

**Issue by Xotic750** [MikeMcl/bignumber.js#76]
Some time ago I mentioned, on big.js https://github.com/MikeMcl/big.js/issues/43, a way to preserve information under the following condition
```
var x = new BigNumber(-0).valueOf();
```
You said it was something you would consider. I see that the string returned is still '0' and not '-0' and I was wondering if you had added it to some other method, as I hadn't noticed it anywhere?

**Comment by MikeMcl** [comment]
Okay, I've just pushed this change. `valueOf` and `toJSON` now include the sign with negative zero.

I have made the same change in the next major update for *decimal.js*, which is a few weeks away, and then I will make it in *big.js* .

Thanks for the nudge.

**Comment by Xotic750** [comment]
No problem, that's great! ;)
