### ISSUE TITLE
BigNumber fails to load in Electron apps

### ISSUE THREAD

**Issue by aakilfernandes** [MikeMcl/bignumber.js#77]
Not sure if you're familiar with Electron, but its a way of pacakging web apps as desktop apps. BigNumber fails to load in Electron apps due to this line:

https://github.com/MikeMcl/bignumber.js/blob/master/bignumber.js#L2685

Electron automatically creates a `module` object in the browser which makes bigNumber think its a node environment.

I'm not sure what the solution is here. Is there an alternative to detecting a node environment?

**Comment by MikeMcl** [comment]
I've just tried it and you are right that the library does not load using, for example,

    <script src="./bignumber.js"></script>

in an html page in an electron app.

But it does seem to load fine using `require`, so it's just a matter of instead using, for example,

    var BigNumber = require('./bignumber');

within script tags in an html page, or within any *.js* files.
