### ISSUE TITLE
losing precision while calculating with multiple BigNumbers

### ISSUE THREAD

**Issue by krachtstefan** [MikeMcl/bignumber.js#80]
I just stumbled about a rounding issue which makes me wonder how to combine multiple BigNumber in calculations. Here is a very basic example to illustrate my problem

```javascript
new BigNumber(1).dividedBy(new BigNumber(1).dividedBy(2.2)).toString() 
-> "2.20000000000000000002" // 1/(1/2.2) should be 2.2
```
I seem understand why this happens (I'm losing precision with the second BigNumber which will will round its value according to ```DECIMAL_PLACES```) but I just wonder how to correctly solve this calculation.

**Comment by MikeMcl** [comment]
As `1 / 2.2`, i.e. `5 / 11`, has an infinite number of digits after the decimal point, it cannot be represented exactly by a single BigNumber. 

The usual approach to this sort of thing is to perform the calculation to a higher precision, then round the result,

    BigNumber.config({DECIMAL_PLACES: 21});
    new BigNumber(1).dividedBy(new BigNumber(1).dividedBy(2.2)).round(20).toString();
    "2.2"

**Comment by krachtstefan** [comment]
Well explained. Thanks for your feedback!

**Comment by krachtstefan** [comment]
Sorry for reopening this issue but after implementing your suggested solution, I found out that this "sometimes" doesn't seem to work as expected.

Here is an example: ```9.12345678901234 / 1609.344``` equals ```0.0056690532223143964248787083...``` and has an infinite number of digits as well.

The regular approach of solving this would be
```javascript
new BigNumber(9.12345678901234).dividedBy(new BigNumber(1609.344)).toString()
-> 0.00566905322231439642
```
This works well and rounds the result perfectly to 20 digits.

But to solve my initial problem from the first post, I implemented the alternative method which ends up in a wrong result:

```javascript
BigNumber.config({DECIMAL_PLACES: 21})
new BigNumber(9.12345678901234).dividedBy(new BigNumber(1609.344)).round(20).toString()
-> 0.00566905322231439643
```

Am I missing something?

**Comment by MikeMcl** [comment]
The results are different because the latter code is rounding twice.

```js
BigNumber.config({DECIMAL_PLACES: 21});
var n = new BigNumber(9.12345678901234).dividedBy(1609.344);
n.toString();             // "0.005669053222314396425"
n.round(20).toString();   // "0.00566905322231439643"
```

If you don't want the division to round up, then change the rounding mode  

```js
BigNumber.config({ROUNDING_MODE: BigNUmber.ROUND_DOWN});
```
or set a higher initial precision.

```js
BigNumber.config({DECIMAL_PLACES: 25});
var n = new BigNumber(9.12345678901234).dividedBy(1609.344);
n.toString();             // "0.0056690532223143964248787"
n.round(20).toString();   // "0.00566905322231439642"
```

**Comment by krachtstefan** [comment]
That worked well. Thank you Mike! 
```javascript
// You should add a donate button to your repo, I owe you a coffee ;) 
```
