### ISSUE TITLE
new BigNumber

### ISSUE THREAD

**Issue by naddison36** [MikeMcl/bignumber.js#81]
In version 1.5.0 I could do the following
```js
var BigNumber = require('bignumber.js');
var testBN = BigNumber(999);
```
After upgrading to 2.1.0, I get the following error
```log
/Users/nick/.nvm/v0.10.40/bin/node testBN.js

/Users/nick/Documents/workspaces/bigNumberTest/node_modules/bignumber.js/bignumber.js:1209
            throw error;
                  ^
BigNumber Error: BigNumber() constructor call without new: 999
    at raise (/Users/nick/Documents/workspaces/bigNumberTest/node_modules/bignumber.js/bignumber.js:1177:25)
    at BigNumber (/Users/nick/Documents/workspaces/bigNumberTest/node_modules/bignumber.js/bignumber.js:162:29)
    at Object.<anonymous> (/Users/nick/Documents/workspaces/bigNumberTest/testBN.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

v2.1.0 works if I do
```js
var BigNumber = require('bignumber.js');
var testBN = new BigNumber(999);
```

The package.json for this is simply
```js
{
  "dependencies": {
    "bignumber.js": "2.1.0"
  }
}
```

Is this a bug? Or have I done something wrong?
Or do I need to change all my usages of BigNumber to include the new operator?

**Comment by MikeMcl** [comment]
From v2.0.1, `new` is required unless `ERRORS` is set to `false`.

    BigNumber.config({ ERRORS: false });

**Comment by naddison36** [comment]
Ok. I'll start using new BigNumber going forward and set {ERRORS: false} until the old code is converted.

Thanks

**Comment by novomanish** [comment]
This supposed improvement has certain drawback. For example
var a = ["1", "2"];
I can do 
a.map(Number)

but I can't do
a.map(BigNumber)

That is bad.

**Comment by CaptJakk** [comment]
Yeah this seriously screws with an FP style. Is there any way we can get this functionality back without having to custom config? Is there a way to get something like this:

```
BigNumber.of = x => new BigNumber(x)
```

I'd be happy to put in a PR but I don't want to spend a ton of time on testing and documentation if the author is opposed to this existing.

**Comment by MikeMcl** [comment]
Okay Captain, from *v5.0.0*, which I've just published, no error will be thrown if the constructor is called without `new`.
