### ISSUE TITLE
15 digit limitation can be wrong

### ISSUE THREAD

**Issue by 1simonfish** [MikeMcl/bignumber.js#84]
I found issue #11, referring to the 15 digit limit.  

```
x = new BigNumber(Number.MAX_SAFE_INTEGER)
```
should be legal. We're using BigNumber as a replacement for BigInteger, and having to convert legal integers to strings just to convert them to BigNumbers is inefficient. Surely there's a more efficient way to do this?

**Comment by MikeMcl** [comment]
I've nothing to add to the very long reply I gave in #11. The following will prevent the error.

```
// There's little reason to have ERRORS true unless debugging
BigNumber.config({ ERRORS: false });
```

Also, any non-integers or large integers are converted to a string anyway by the BigNumber constructor, so there is no real inefficiency introduced anyway.
