### ISSUE TITLE
Feature Submission: Modular Exponentiation

### ISSUE THREAD

**Issue by jasonshaev** [MikeMcl/bignumber.js#86]
I'd like to submit a pull request implementing modular exponentiation as a combined function (as opposed to `.pow(n).mod(m)`. Modular exponentiation is an important operation in many cryptographic applications where the size of the numbers involved necessitates an efficient implementation. Specifically, I have implemented this algorithm: https://en.wikipedia.org/wiki/Modular_exponentiation#Right-to-left_binary_method

Would you be willing to accept such a pull request (including tests)? If so, I'm curious how you would prefer the implementation. Specifically, I can create an entirely new function, `powMod(n, m)` or add an optional parameter (the modulus) to the existing `pow` function.

Thanks for your time.

**Comment by MikeMcl** [comment]
If a new method was to be added to the API, it would have to conform to the current naming scheme, i.e. that all methods have a non-abbreviated version, and be something like `toModularPower` or `toPowerModulo`, with a short-form of something like `powMod` as you suggest.

I think I would prefer just adding the optional parameter to the existing `toPower`/`pow` method.

I would be happy to accept the addition of modular exponentiation functionality to the library, though of course I cannot guarantee that any particular pull request will be accepted before I have seen it.

**Comment by jasonshaev** [comment]
Thanks for your feedback. I implemented the algorithm by adding an optional parameter to the existing `toPower/pow` method. Please let me know what you think of the implementation when you have a free moment!

https://github.com/MikeMcl/bignumber.js/pull/87

**Comment by jasonshaev** [comment]
Hey @MikeMcl sorry for my lack of responsiveness on this, been very busy the last few months. When I get some free time I'll revisit and reopen :)

**Comment by MikeMcl** [comment]
No problem, thanks for the work you submitted. I will look at it again myself when time permits.

One issue was that the method arguments need to be integers, so I asked myself is it then suitable for this library, which doesn't just work with integers. And then I thought well it at least needs to be a separate method, `intPowMod` or something.

I think you have given all the input you need to on this. I still have various decisions to make about it, so it is not a pull request that you can complete at the moment.
