### ISSUE TITLE
Feature Request: In-/ Decrement Operator

### ISSUE THREAD

**Issue by nottinhill** [MikeMcl/bignumber.js#88]
It would be really nice if we had something like a `++` and `--` operator to in-/decrement an object without having to do an extra assignment. Or even better a `+=` and `-=` operator.

**Comment by MikeMcl** [comment]
Yes, I did consider implementing the operators as method names, for example

    a = new BigNumber(1);
    b = a['+'](2);
    c = a['/'](3); 

And as you suggest

    a['++']();
    a['+='](2);

Which operators could be used in this way?
    
    + - * / % < > <= >= == != ++ -- += -= *= /= %= 

Would this be a worthwhile addition, or just unnecessary noise in the API?

**Comment by Meekohi** [comment]
@nottinhill Javascript does not support operator overloading, so unfortunately a clean implementation of this is not possible.

In my opinion requiring the brackets is much grosser than just using named functions. i.e. I would much rather `a.increment();` than `a['++']();`.

(Actually I just learned there are some wizard AST tricks for doing operator overloading, but you have pre-process your functions using this technique: https://github.com/kushal-likhi/operator-overloading-js)

**Comment by MikeMcl** [comment]
Yes, I'm not going to include the operators as method names, and I don't want to add `increment` etc. either.
