### ISSUE TITLE
Better bound on tooManyDigits ("has more than 15 significant digits")

### ISSUE THREAD

**Issue by Meekohi** [MikeMcl/bignumber.js#91]
Was using https://github.com/felixge/node-mysql with `supportBigNumbers:true` and `bigNumberStrings:false`, but found that I would still get the `tooManyDigits` error occasionally:

> number type has more than 15 significant digits

After digging in, I was amused to find that `mysql` is actually using `bignumber.js` under the hood, but is calculating more precisely when to switch from JS Number to a string. They check the binary representation to see if a number is "too big" to be represented accurately, which makes sense because they have to twiddle bits anyway come from MySQL.

I was wondering if it would make sense in `bignumber.js` to add a simple test to the constructor to see, if the number is an integer, whether the number is `(val < Number.MAX_VALUE && val > Number.MIN_VALUE)`? This would allow a wider range of "safe" numbers to be created without throwing an error (in particular, all the 16-digit integers < 9007199254740992 are okay in Javascript).

**Comment by Meekohi** [comment]
Link to relevant code in `mysql` for anyone curious. Not proposing we do this since it is probably overkill: https://github.com/felixge/node-mysql/blob/a9cbba154263f9d299ecfe14b97dc5fd51ae1c37/lib/protocol/Parser.js#L224

**Comment by MikeMcl** [comment]
Okay, from *v2.2.0*, all integers up to `Number.MAX_SAFE_INTEGER` are now accepted.
