### ISSUE TITLE
POW_PRECISION defaults to 100

### ISSUE THREAD

**Issue by jhinrichsen** [MikeMcl/bignumber.js#92]
Dear Mike,

struggling for a couple of hours why my pow() results are broke (or at least a little bit broke), i finally stumbled across POW_PRECISION. According to the principle of least astonishment (POLA), POW_PRECISION should be set to a default 0, so that pow() results are correct out of the box, without any performance tweaks. As of now, pow() results are are only correct for the first N digits, after that they are '0'-ed.

Other than that, thanks for your wonderful library.

**Comment by MikeMcl** [comment]
Yes, I agree with you. I think the reason I set the default to 100 was so that the performance of the method was good out of the box, even if the exponent was very large.

I'll consider changing it to 0 for ther next update.

**Comment by MichaelLeeHobbs** [comment]
Ah, I'm guessing that is why the follow code breaks on an input of 1 1 20

function processData(input) {
    //Enter your code here
    input = processInput(input);
    var fn = fnGen(parseInt(input[0]), parseInt(input[1]));
    console.log(fn(parseInt(input[2])).toString(10));
    
}

function fnGen(n1, n2) {
    var bn1 = new BigNumber(n1);
    var bn2 = new BigNumber(n2);

    var fn = function(n) {
        if (n === 1) return bn1;
        if (n === 2) return bn2;
        
        var fOfN1 = bn1;
        var fOfN2 = bn2;
        
        for (var i = 3; i <= n; i++){
            var current = fOfN2.pow(2).add(fOfN1);
            fOfN1 = fOfN2;
            fOfN2 = current;
        }
        
        return current;
    }
    return fn;
}

function processInput(input){
    input = input.split(" ");
    return input;
}

process.stdin.resume();
process.stdin.setEncoding("ascii");
_input = "";
process.stdin.on("data", function (input) {
    _input += input;
});

process.stdin.on("end", function () {
   processData(_input);
});

**Comment by MikeMcl** [comment]
Fixed in v3.0.0.
