### ISSUE TITLE
toSignificantDigits

### ISSUE THREAD

**Issue by aft-luke** [MikeMcl/bignumber.js#94]
Am I missing something obvious here? I see `toDigits()` and `toSignificantDigits` and `toSD()` among the docs, but I cannot for the life of me find those functions (or how to use them) when working with the actual library.

```
let n = new BigNumber(12.3)
n.toDigits() // another BigNumber { s: 1, e: 1, c: Array[2] }, what I want is '12.3'

n.toSignificantDigits() // not a function
n.toSD() // not a function
n.toDigits().toSignificantDigits() // not a function
```

**Comment by MikeMcl** [comment]
It's [`toDigits()`](http://mikemcl.github.io/bignumber.js/#toD), and you need to call `toString()` or `valueOf()` on the returned object to get the string `'12.3'`.

`toSignificantDigits` and `toSD` are present in the API of [decimal.js](https://github.com/MikeMcl/decimal.js) not here.
