### ISSUE TITLE
Why is the exponent in toPower() limited to < MAX_SAFE_INT?

### ISSUE THREAD

**Issue by mlbk0** [MikeMcl/bignumber.js#95]
In short, I'm getting this error:

```
var p = new BigNumber('92957395832410175236');
var x = new BigNumber(2).toPower(p, p);
// BigNumber Error: pow() exponent out of range: 92957395832410175236
```

I looked into the source code and I don't understand why the exponent is bounded in that way.

I'm implementing an ElGamal scheme and trying to exponentiate a number by a large prime.

From the source code it seems the exponent in toPower has an upper bound of 2^53 -1. I need to exponentiate by much larger numbers for standard operations. 

Is there any way around this?! Maybe I'm missing something obvious.

**Comment by MikeMcl** [comment]
There was no modulus parameter in earlier versions of this library, so the upper bound seemed reasonable given that the maximum exponent of any Big number is 1000000000.

Yes, for modular power operations it is perhaps unnecessarily restricitve.

I'll try to have a look at it this weekend.

**Comment by MikeMcl** [comment]
A big integer library would be better for this kind of crypto work, so I've decided against making the significant changes it would require.

Just for interest, how big would would these large primes be?

**Comment by nVVEBd** [comment]
This is a bit of topic but could this library handle a 256bit number?

I want to convert SHA256 hex value to a number (and then into binary). Finish is truncating the binary to n-bits.

**Comment by MikeMcl** [comment]
@nVVEBd 

The answer is yes, this library can do that. See the (documentation)[http://mikemcl.github.io/bignumber.js/] and try it in the console.
