### ISSUE TITLE
Provide default export for ES6 / TypeScript users

### ISSUE THREAD

**Issue by felixfbecker** [MikeMcl/bignumber.js#97]
Currently, BigNumber only uses `module.export` to export itself. For users of ES6 and TypeScript it would be nice to have `BigNumber` also as a named export or default export, e.g. if you could do
```js
module.exports = constructorFactory();
module.exports.BigNumber = module.exports;
module.exports.default = module.exports;
```
which would allow to do
```js
import {BigNumber} from 'bignumber';
```
I'm currently writing TypeScript definitions for BigNumber and this would simplify things a lot, as I could export other interfaces besides the main `BigNumber` class.

**Comment by MikeMcl** [comment]
This seems reasonable, but please can you further explain why you want to be able to use

    import {BigNumber} from 'bignumber';

rather than

    import BigNumber from 'bignumber';

I don't yet know enough about TypeScript to understand why it "would simplify things a lot", or how it would enable you to "export other interfaces besides the main BigNumber class".

**Comment by felixfbecker** [comment]
@MikeMcl that is just a matter of style. You export the `BigNumber` class, the `BigNumberError` class (for proper `instanceof` checks) and the TypeScript definitions can also export some interfaces. Then in addition, you say `BigNumber` should be the default export.
```ts
import {BigNumber, BigNumberError, Configuration} from 'bignumber.js';
// easier than import {default as BigNumber, BigNumberError} from 'bignumber.js';

try {
  const x = new BigNumber(123);
} catch (e) {
  if (e instanceof BigNumberError) {
    // TypeScript now knows that e has all the properties of BigNumberError
  }
}
```
the definitions would look like this:
```ts
declare module 'bignumber.js' {
  export interface Configuration {
    DECIMAL_PLACES: number;
  }
  export class BigNumber {
    static config(config: Configuration): Configuration;
  }
  export class BigNumberError extends Error {}
  export default BigNumber;
}
```

For the legacy `module.exports` TypeScript has a special syntax, `export = `. But when you use it you can only export _one_ item:
```ts
declare module 'bignumber.js' {
  // cannot export this :(
  interface Configuration {
    DECIMAL_PLACES: number;
  }
  export class BigNumber {
    static config(config: Configuration): Configuration;
  }
  export = BigNumber;
}
```
and you have to use `require()` instead of `import`, which prevents you from compiling to ES6.
```ts
import BigNumber = require('bignumber.js');
```

TypeScript definitions don't only help TypeScript users, but power editor autocompletion in editors for JavaScript users. It would also benefit Node users as `import`/`export` may already land in Node 7 and all users who write front-end code in ES6.

**Comment by felixfbecker** [comment]
If you are interested, check out https://github.com/felixfbecker/typed-bignumber.js

**Comment by MikeMcl** [comment]
I've played around with it and yes it seems to work, but its hacky and irritating to have to add two redundant properties (which will show up in intellisense) to the BigNumber class so that ES6 imports work. 

Is this something other libraries have done?

**Comment by felixfbecker** [comment]
Yes, [sequelize](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L1388-L1390) for example. I also saw it in other libraries.

It also has the added benefit that you could export the BigNumberError class (and possibly more in the future) aswell, all while maintaining BC. In the end, `module.exports` was never a standard, it was an extension by NodeJS. Both CommonJS and ES6 use named and default exports.

Typings work as they are, but what would maybe make it feel a bit "hacky" for ES5 users (honestly I think most wont even notice) would make it way less "hacky" for ES6 and TS users.

**Comment by MikeMcl** [comment]
Okay, I just pushed v2.4.0. 

Let me know if there any issues.

Great work on the definitions by the way.
