### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by OussamaRomdhane** [MikeMcl/bignumber.js#98]
Hi, as far as I can tell you have not created an npm package for this lib so I was just wandering if I can fork this and make an npm package out of it, I currently need this in another npm package I'm working on. 
Thanks

**Comment by gastonelhordoy** [comment]
https://www.npmjs.com/package/bignumber.js

**Comment by OussamaRomdhane** [comment]
How couldn't I find that is beyond me, thanks :smile:
