### ISSUE TITLE
Fractions can't be multiplied by bignumbers

### ISSUE THREAD

**Issue by gitKad** [MikeMcl/bignumber.js#99]
I can't multiply _bignumbers_ and _fractions_. Here's a failing test I added to function\arithmetic\multiply.test.js:

```
it('should multiply mixed fractions and big numbers', function() {
  assert.equal(multiply(math.bignumber('2'), math.fraction(1,3)), math.fraction(2,3));
  assert.equal(multiply(math.fraction(1,3), math.bignumber('2')), math.fraction(2,3));
});
```

**Comment by josdejong** [comment]
I guess you should report this at the [mathjs](https://github.com/josdejong/mathjs/) project instead of bignumber.js?

**Comment by gitKad** [comment]
Ha, this is what I intended! Weird mistake; sorry about that! :-)
